version: '3'

services:
  db:
    environment:
      POSTGRES_DB: db_app
      POSTGRES_USER: db_user
      POSTGRES_PASSWORD: db_pass
    restart: always
    image: postgres:9.6-alpine
    ports:
      - "5432:5432"

  web:
    build:
      context: .
      dockerfile: ./docker/local/Dockerfile.web
    command: /start.sh
    environment:
      POSTGRES_HOST: db
      POSTGRES_PORT: 5432
      PROFILES_SERIALIZER: "content.serializers.PlantSerializer"
    volumes:
      - .:/app
    depends_on:
      - db
    ports:
      - "8000:8000"
