# Generated by Django 3.0.4 on 2020-03-23 17:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0002_create_plant_model'),
    ]

    operations = [
        migrations.CreateModel(
            name='Leaf',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nerves', models.CharField(choices=[('str', 'streifennervig'), ('net', 'netznervig'), ('fie', 'fiedernervig'), ('fin', 'fingernervig'), ('fus', 'fußnervig'), ('gab', 'gabelnervig')], max_length=3, verbose_name='Blattnerven')),
                ('cnt_germ', models.IntegerField(choices=[(1, 1), (2, 2)], verbose_name='Anzahl der Keimblätter')),
                ('att_axis', models.CharField(choices=[('ges', 'gestielt'), ('sit', 'sitzend/ungestielt'), ('ste', 'stengelumfassend'), ('hal', 'halbstengelumfassend'), ('dur', 'durchwachsen'), ('ver', 'verwachsen'), ('sch', 'scheidig verwachsen'), ('her', 'herablaufend'), ('rei', 'reitend'), ('hin', 'hinfällig')], max_length=3, verbose_name='Anheftung an Sprossachse')),
                ('sheath', models.CharField(default='-', max_length=100, verbose_name='Blattscheide')),
                ('pos_axis', models.CharField(choices=[('gru', 'grundständig'), ('wec', 'wechselständig/spiralig'), ('zwe', 'zweizeilig/distich'), ('dre', 'dreizeilig/tristich'), ('geg', 'gegenständig'), ('kre', 'kreuzgegenständig/dekussiert'), ('gep', 'gepaart'), ('qui', 'quirlig/wirtelig'), ('sch', 'scheinquirlig'), ('dac', 'dachziegelig'), ('ein', 'einseitig'), ('ges', 'gescheitelt')], max_length=3, verbose_name='Stellung an Sprossachse')),
                ('spr_whole', models.CharField(choices=[('ein', 'einfach'), ('zus', 'zusammengesetzt')], max_length=3, verbose_name='Blattspreite gesamt')),
                ('dep_cuts', models.CharField(choices=[('gan', 'ganz/ungeteilt'), ('gel', 'gelappt'), ('gep', 'gespalten'), ('get', 'geteilt'), ('ges', 'geschnitten')], max_length=3, verbose_name='Tiefe von Einschnitten')),
                ('arr_cuts', models.CharField(choices=[('han', 'handförmig/fingerförmig'), ('hgl', 'handförmig gelappt'), ('hgt', 'handförmig geteilt'), ('hgs', 'handförmig geschnitten'), ('gef', 'gefingert'), ('fie', 'fiederförmig/fiederig'), ('fil', 'fiederlappig'), ('fip', 'fiederspaltig'), ('fit', 'fiederteilig'), ('fis', 'fiederschnittig'), ('paa', 'paarig gefiedert'), ('unp', 'unpaarig gefiedert'), ('unf', 'unterbrochen fiederschnittig'), ('ung', 'unterbrochen gefiedert'), ('dog', 'doppelt gefiedert'), ('meh', 'mehrfach gefiedert'), ('dre', 'dreizählig'), ('dod', 'doppelt dreizählig'), ('lei', 'leierförmig'), ('sch', 'schrotsägeförmig'), ('kam', 'kammförmig'), ('fug', 'fußförmig geschnitten'), ('fuz', 'fußförmig zusammengesetzt')], max_length=3, verbose_name='Anordnung von Einschnitten/Blättchen')),
                ('arr_special', models.BooleanField(default=False, verbose_name='Anordnung ist buchtig.')),
                ('form', models.CharField(choices=[('kre', 'kreisrund'), ('run', 'rundlich'), ('ell', 'elliptisch'), ('eif', 'eiförmig'), ('ver', 'verkehrteiförmig'), ('spa', 'spatelförmig/spatelig'), ('len', 'lanzettlich'), ('eil', 'eilanzettlich'), ('lae', 'länglich'), ('lin', 'linealisch/lineal'), ('nad', 'nadelförmig'), ('pfr', 'pfriemlich'), ('bor', 'borstenförmig/borstlich'), ('fad', 'fadenförmig/fädlich'), ('bin', 'binsenartig'), ('roe', 'röhrig'), ('ser', 'schwertförmig'), ('dre', 'dreieckig'), ('kei', 'keilförmig'), ('rau', 'rautenförmig/rhombisch'), ('her', 'herzförmig'), ('vhe', 'verkehrtherzförmig'), ('nie', 'nierenförmig'), ('pfe', 'pfeilförmig'), ('spi', 'spießförmig'), ('gei', 'geigenförmig'), ('sup', 'schuppenförmig'), ('sil', 'schildförmig')], max_length=3, verbose_name='Gestalt des Blattes/der Blättchen')),
                ('count', models.CharField(default='', max_length=200, verbose_name='Anzahl Blättchen')),
                ('leaflets', models.CharField(choices=[('gan', 'ganzrandig'), ('ges', 'gesägt'), ('dop', 'doppelt gesägt'), ('rue', 'rückwärts gesägt'), ('gez', 'gezähnt'), ('gzt', 'gezähnelt'), ('gef', 'gefranst'), ('gek', 'gekerbt'), ('geb', 'gebuchtet'), ('ges', 'geschweift'), ('bew', 'bewimpert'), ('vor', 'vorwärts rauh'), ('rra', 'rückwärts rauh')], max_length=3, verbose_name='Spreiten/Blättchen')),
                ('texture', models.CharField(choices=[('kra', 'krautig'), ('fle', 'fleischig'), ('led', 'lederig'), ('hae', 'häutig/trockenhäutig'), ('imm', 'immergrün'), ('sta', 'starr/steif')], max_length=3, verbose_name='Beschaffenheit')),
                ('sur_texture', models.CharField(choices=[('gla', 'glatt'), ('run', 'runzelig'), ('rau', 'rauh'), ('vra', 'vorwärts rauh'), ('ber', 'bereift'), ('bes', 'bestäubt/bemehlt'), ('pap', 'papillös'), ('pun', 'punktiert'), ('swi', 'schwielig'), ('kah', 'kahl'), ('ver', 'verkahlend'), ('fla', 'flaumhaarig/weichhaarig'), ('sei', 'seidenhaarig'), ('spi', 'spinnwebig'), ('flo', 'flockig'), ('sam', 'samthaarig'), ('fil', 'filzig'), ('wol', 'wollig'), ('zot', 'zottig'), ('rah', 'rauhaarig'), ('ste', 'steifhaarig'), ('gew', 'gewimpert'), ('dru', 'drüsenhaarig'), ('ste', 'sternhaarig'), ('sdh', 'schildhaarig'), ('sup', 'schuppenhaarig/schuppig'), ('sue', 'schülferig'), ('bae', 'bärtig'), ('ach', 'achselbärtig'), ('nac', 'nackt')], max_length=3, verbose_name='Oberflächenbeschaffenheit')),
                ('side_leaf', models.CharField(choices=[('gan', 'ganzrandig'), ('ges', 'gesägt'), ('dop', 'doppelt gesägt'), ('rue', 'rückwärts gesägt'), ('gez', 'gezähnt'), ('gzt', 'gezähnelt'), ('gef', 'gefranst'), ('gek', 'gekerbt'), ('geb', 'gebuchtet'), ('gew', 'geschweift'), ('bew', 'bewimpert'), ('vor', 'vorwärts rauh'), ('rur', 'rückwärts rauh')], max_length=3, verbose_name='Nebenblattrand')),
                ('diam', models.CharField(choices=[('zur', 'zurückgerollt/umgerollt'), ('ein', 'eingerollt'), ('zus', 'zusammengerollt'), ('gef', 'gefalzt/gefaltet'), ('rin', 'rinnig'), ('gek', 'gekielt'), ('dop', 'doppelrillig')], max_length=3, verbose_name='Querschnitt')),
                ('sp_ground', models.CharField(choices=[('kei', 'keilig/keilförmig'), ('ver', 'verschmälert'), ('abg', 'abgerundet'), ('ges', 'gestutzt'), ('her', 'herzförmig'), ('nie', 'nierenförmig'), ('pfe', 'pfeilförmig'), ('spi', 'spießförmig')], max_length=3, verbose_name='Spreitengrund')),
                ('sp_top', models.CharField(choices=[('abg', 'abgerundet'), ('ges', 'gestzutzt'), ('stu', 'stumpf'), ('spi', 'spitz'), ('zug', 'zugespitzt'), ('beg', 'begrannt'), ('sta', 'stachelspitze'), ('haa', 'haarspitzig'), ('bes', 'bespitzt'), ('aus', 'ausgerandet')], max_length=3, verbose_name='Spreitengrund')),
                ('specialty', models.CharField(default='', max_length=200, verbose_name='Besondere Merkmale')),
                ('plant', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='leaf', to='content.Plant', verbose_name='Pflanze')),
            ],
        ),
    ]
