# Generated by Django 3.0.4 on 2020-03-23 17:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("content", "0003_create_leaf_model"),
    ]

    operations = [
        migrations.CreateModel(
            name="Sprout",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "appear",
                    models.CharField(
                        choices=[("k", "krautig"), ("h", "holzig")],
                        default="",
                        max_length=1,
                        verbose_name="Erscheinung",
                    ),
                ),
                (
                    "pos",
                    models.CharField(
                        choices=[
                            ("auf", "aufrecht"),
                            ("aua", "aufrecht-abstehend"),
                            ("abs", "abstehend"),
                            ("spa", "sparrig"),
                            ("zur", "zurückgeschlagen"),
                            ("lie", "liegend"),
                            ("kri", "kriechend"),
                            ("aus", "aufsteigend/aufstrebend"),
                            ("gek", "gekniet"),
                            ("ueb", "übergebogen"),
                            ("nic", "nickend"),
                            ("hae", "hängend"),
                            ("flu", "flutend"),
                            ("Ran", "Rankenpflanze"),
                            ("Win", "Windepflanze"),
                            ("Spr", "Spreizklimmer"),
                            ("Wur", "Wurzelkletterer"),
                            ("hor", "horstig"),
                            ("loc", "lockerrasig"),
                        ],
                        max_length=3,
                        verbose_name="Stellung",
                    ),
                ),
                (
                    "thick_flesh",
                    models.BooleanField(default=False, verbose_name="Dickfleischig"),
                ),
                ("milk", models.BooleanField(default=False, verbose_name="Milchsaft")),
                (
                    "rose",
                    models.BooleanField(default=False, verbose_name="Grundblattrose"),
                ),
                (
                    "leafly",
                    models.CharField(
                        choices=[("nur", "Nur am Grund"), ("auc", "Auch über Grund")],
                        max_length=3,
                        verbose_name="Beblätterung",
                    ),
                ),
                (
                    "diam",
                    models.CharField(
                        choices=[
                            ("sti", "stielrund"),
                            ("hal", "halbstielrund"),
                            ("zus", "zusammengedrückt"),
                            ("zwe", "zweischneidig"),
                            ("kan", "kantig"),
                            ("stu", "stumpfkantig"),
                            ("ger", "gerieft /gerillt"),
                            ("gef", "gefurcht"),
                            ("kan", "kantig gefurcht /scharfkantig"),
                            ("gri", "gerippt"),
                            ("gfl", "geflügelt"),
                            ("kno", "knotig"),
                        ],
                        max_length=3,
                        verbose_name="Stellung",
                    ),
                ),
                (
                    "sur_texture",
                    models.CharField(
                        choices=[
                            ("gla", "glatt"),
                            ("run", "runzelig"),
                            ("rau", "rauh"),
                            ("vra", "vorwärts rauh"),
                            ("ber", "bereift"),
                            ("bes", "bestäubt/bemehlt"),
                            ("pap", "papillös"),
                            ("pun", "punktiert"),
                            ("swi", "schwielig"),
                            ("kah", "kahl"),
                            ("ver", "verkahlend"),
                            ("fla", "flaumhaarig/weichhaarig"),
                            ("sei", "seidenhaarig"),
                            ("spi", "spinnwebig"),
                            ("flo", "flockig"),
                            ("sam", "samthaarig"),
                            ("fil", "filzig"),
                            ("wol", "wollig"),
                            ("zot", "zottig"),
                            ("rah", "rauhaarig"),
                            ("ste", "steifhaarig"),
                            ("gew", "gewimpert"),
                            ("dru", "drüsenhaarig"),
                            ("ste", "sternhaarig"),
                            ("sdh", "schildhaarig"),
                            ("sup", "schuppenhaarig/schuppig"),
                            ("sue", "schülferig"),
                            ("bae", "bärtig"),
                            ("ach", "achselbärtig"),
                            ("nac", "nackt"),
                        ],
                        max_length=3,
                        verbose_name="Oberflächenbeschaffenheit",
                    ),
                ),
                (
                    "blade",
                    models.CharField(default="", max_length=200, verbose_name="Halm"),
                ),
                (
                    "cluster",
                    models.CharField(default="", max_length=200, verbose_name="Horst"),
                ),
                (
                    "plant",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="sprout",
                        to="content.Plant",
                        verbose_name="Pflanze",
                    ),
                ),
            ],
        ),
    ]
