# Generated by Django 3.0.5 on 2020-05-15 09:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("content", "0016_add_leaflet_choice"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="blossom",
            options={"verbose_name": "Blüte", "verbose_name_plural": "Blüten"},
        ),
        migrations.AlterModelOptions(
            name="fruit",
            options={"verbose_name": "Frucht", "verbose_name_plural": "Früchte"},
        ),
        migrations.AlterModelOptions(
            name="leaf",
            options={"verbose_name": "Blatt", "verbose_name_plural": "Blätter"},
        ),
        migrations.AlterModelOptions(
            name="plant",
            options={"verbose_name": "Pflanze", "verbose_name_plural": "Pflanzen"},
        ),
        migrations.AlterModelOptions(
            name="sprout",
            options={"verbose_name": "Keim", "verbose_name_plural": "Keime"},
        ),
    ]
