# Generated by Django 3.0.8 on 2020-07-06 13:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0017_provide_verbose_names'),
    ]

    database_operations = [
        migrations.AlterModelTable('Plant', 'dive_content_plant'),
        migrations.AlterModelTable('Leaf', 'dive_content_leaf'),
        migrations.AlterModelTable('Sprout', 'dive_content_sprout'),
        migrations.AlterModelTable('Fruit', 'dive_content_fruit'),
        migrations.AlterModelTable('Blossom', 'dive_content_blossom')
    ]
    operations = [
        migrations.SeparateDatabaseAndState(
            database_operations=database_operations
        )
    ]
