# Generated by Django 3.0.4 on 2020-03-23 15:34

import django.contrib.postgres.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("dive_content", "0001_create_tree_node_model"),
    ]

    operations = [
        migrations.CreateModel(
            name="Plant",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100, verbose_name="Art")),
                (
                    "trivial_name",
                    models.CharField(max_length=100, verbose_name="Trivialname"),
                ),
                (
                    "habitat",
                    django.contrib.postgres.fields.ArrayField(
                        base_field=models.CharField(
                            choices=[
                                ("sch", "Schlammfluren"),
                                ("roe", "Röhrichte"),
                                ("sae", "Säume"),
                                ("sta", "Stauden"),
                                ("gru", "Grünland und Zwergstrauchheiden"),
                                ("rud", "Ruderalvegetation"),
                                ("aec", "Äcker"),
                                ("wei", "Weinberge"),
                                ("int", "Intensivgrünland"),
                                ("par", "Parks"),
                                ("gae", "Gärten"),
                                ("tri", "Trittpflanzengesellschaften"),
                                ("fel", "Felsbiotope"),
                                ("aue", "Auenwälder"),
                                ("geb", "Gebüsche"),
                                ("ext", "Extensivgrünland oder natürlicher Rasen"),
                                ("wae", "Wälder"),
                                ("ufe", "Ufer"),
                            ],
                            max_length=3,
                        ),
                        blank=True,
                        size=None,
                        verbose_name="Lebensraum",
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("e", "einheimisch"),
                            ("a", "Archaeophyt"),
                            ("n", "Neophyt"),
                        ],
                        max_length=1,
                        verbose_name="Status",
                    ),
                ),
                (
                    "interaction",
                    models.CharField(
                        choices=[
                            ("par", "parasitisch"),
                            ("nip", "nicht parasitisch"),
                            ("obl", "obligate Mykorrhiza"),
                            ("fak", "fakultative Mykorrhiza"),
                        ],
                        max_length=3,
                        verbose_name="Interaktionen",
                    ),
                ),
                (
                    "ground",
                    django.contrib.postgres.fields.ArrayField(
                        base_field=models.CharField(
                            choices=[
                                ("rei", "nährstoffreich"),
                                ("arm", "nährstoffarm"),
                                ("leh", "lehmig"),
                                ("tor", "torfig"),
                                ("san", "sandig"),
                                ("ste", "steinig/felsig"),
                            ],
                            max_length=3,
                        ),
                        blank=True,
                        size=None,
                        verbose_name="Untergrund",
                    ),
                ),
                ("bloom", models.CharField(max_length=200, verbose_name="Blütezeit")),
                (
                    "prime_root",
                    models.CharField(
                        choices=[
                            ("erh", "erhalten"),
                            ("ers", "ersetzt durch sprossbürtige Wurzeln"),
                        ],
                        max_length=3,
                        verbose_name="Primärwurzel",
                    ),
                ),
                ("nodule", models.BooleanField(verbose_name="Wurzelknollen")),
                (
                    "systematics",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        related_name="profiles",
                        to="dive_content.TreeNode",
                        verbose_name="Steckbrief-Ebene",
                    ),
                ),
            ],
        ),
    ]
