# Generated by Django 3.0.4 on 2020-03-23 17:55
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("dive_content", "0003_create_sprout_model"),
    ]

    operations = [
        migrations.CreateModel(
            name="Fruit",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "spread",
                    models.CharField(
                        choices=[("sa", "Samen"), ("sp", "Sporen")],
                        max_length=2,
                        verbose_name="Ausbreitungsform",
                    ),
                ),
                (
                    "pos",
                    models.CharField(
                        choices=[
                            ("fr", "Fruchtknoten"),
                            ("za", "Zapfenschuppe"),
                            ("sp", "Sprossachse"),
                        ],
                        max_length=2,
                        verbose_name="Lage der Samenanlage",
                    ),
                ),
                (
                    "type",
                    models.CharField(
                        choices=[
                            ("nus", "Nuss"),
                            ("kar", "Karyopse"),
                            ("ach", "Achäne"),
                            ("bee", "Beere"),
                            ("ste", "Steinfrucht"),
                            ("bal", "Balgfrucht"),
                            ("hue", "Hülse"),
                            ("kap", "Kapsel"),
                            ("sos", "Schote ohne Scheidewand"),
                            ("smf", "Schote mit falscher Scheidewand"),
                            ("soe", "Schötchen"),
                            ("spa", "Spaltfrucht"),
                            ("kok", "Kokke"),
                            ("dop", "Doppelachäne"),
                            ("bru", "Bruchfrucht"),
                            ("glh", "Gliederhülse"),
                            ("gls", "Gliederschote"),
                            ("kla", "Klausenfrucht"),
                            ("sam", "Sammelbalgfrucht"),
                            ("nue", "Nüsschen"),
                            ("stc", "Steinfrüchtchen"),
                            ("bac", "Balgfrüchtchen"),
                        ],
                        max_length=3,
                        verbose_name="Fruchttyp",
                    ),
                ),
                (
                    "cnt",
                    models.CharField(
                        default="", max_length=200, verbose_name="Samenzahl"
                    ),
                ),
                (
                    "form",
                    models.CharField(default="", max_length=200, verbose_name="Form"),
                ),
                (
                    "wings",
                    models.CharField(
                        default="", max_length=200, verbose_name="Beflügelung"
                    ),
                ),
                (
                    "wings_spec",
                    models.CharField(
                        default="",
                        max_length=200,
                        verbose_name="Beflügelung Besonderheit",
                    ),
                ),
                (
                    "plant",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="fruit",
                        to="dive_content.Plant",
                        verbose_name="Pflanze",
                    ),
                ),
            ],
        ),
    ]
