# Generated by Django 3.0.4 on 2020-03-25 11:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("dive_content", "0005_create_fruit_model"),
    ]

    operations = [
        migrations.CreateModel(
            name="Blossom",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "type",
                    models.CharField(
                        choices=[
                            ("tra", "Traube"),
                            ("ris", "Rispe"),
                            ("ebe", "Ebenstrauß/Corymbus"),
                            ("sct", "Schirmtraube"),
                            ("scr", "Schirmrispe"),
                            ("spi", "Spirre/Trichterrispe"),
                            ("aer", "Ähre"),
                            ("kol", "Kolben"),
                            ("kae", "Kätzchen"),
                            ("zap", "Zapfen"),
                            ("dol", "Dolde"),
                            ("dod", "Doppeldolde"),
                            ("kop", "Kopf"),
                            ("koc", "Köpfchen"),
                            ("kor", "Korb"),
                            ("krc", "Körbchen"),
                            ("zym", "Zyme"),
                            ("ple", "Pleiochasium"),
                            ("dic", "Dichasium"),
                            ("mon", "Monochasium"),
                            ("wic", "Wickel"),
                            ("dow", "Doppelwickel"),
                            ("scq", "Scheinquirl"),
                            ("bue", "Büschel"),
                            ("kna", "Knäuel"),
                            ("thy", "Thyrse"),
                            ("scd", "Scheindolde/Trugdolde"),
                            ("scb", "Scheinblüte/Pseudanthium"),
                        ],
                        max_length=3,
                        verbose_name="Blütenstandtyp",
                    ),
                ),
                (
                    "bl_cnt",
                    models.CharField(
                        default="",
                        max_length=100,
                        verbose_name="Blüten pro Blütenstand",
                    ),
                ),
                (
                    "sym",
                    models.CharField(
                        choices=[
                            ("r", "radiärsymmetrisch/aktinomorph/strahlig"),
                            ("d", "disymmetrisch/bilateral"),
                            ("z", "zygomorph/dorsiventral"),
                            ("a", "asymmetrisch/unregelmäßig"),
                        ],
                        max_length=1,
                        verbose_name="Symmetrie",
                    ),
                ),
                (
                    "parting",
                    models.CharField(
                        choices=[
                            ("gan", "ganz/ungeteilt"),
                            ("gel", "gelappt"),
                            ("gsp", "gespalten"),
                            ("get", "geteilt"),
                            ("ges", "geschnitten"),
                            ("han", "handförmig/fingerförmig"),
                            ("hgl", "handförmig gelappt"),
                            ("hgt", "handförmig geteilt"),
                            ("hgs", "handförmig geschnitten"),
                            ("gef", "gefingert"),
                            ("fie", "fiederförmig/fiederig"),
                            ("fil", "fiederlappig"),
                            ("fsp", "fiederspaltig"),
                            ("fit", "fiederteilig"),
                            ("fis", "fiederschnittig"),
                            ("paf", "paarig gefiedert"),
                            ("upf", "unpaarig gefiedert"),
                            ("unf", "unterbrochen fiederschnittig"),
                            ("ung", "unterbrochen gefiedert"),
                            ("dop", "doppelt gefiedert"),
                            ("meh", "mehrfach gefiedert"),
                            ("dre", "dreizählig"),
                            ("dod", "doppelt dreizählig"),
                            ("lei", "leierförmig"),
                            ("sch", "schrotsägeförmig"),
                            ("kam", "kammförmig"),
                            ("fug", "fußförmig geschnitten"),
                            ("fuz", "fußförmig zusammengesetzt"),
                        ],
                        max_length=3,
                        verbose_name="Blütenstandtyp",
                    ),
                ),
                (
                    "cnt",
                    models.IntegerField(
                        choices=[(3, 3), (4, 4), (5, 5)], verbose_name="Zähligkeit"
                    ),
                ),
                (
                    "hull",
                    models.CharField(
                        choices=[
                            ("dop", "doppelte Blütenhülle (Kalyx + Corolla)"),
                            ("ein", "einfache Blütenhülle (Perigon)"),
                            ("feh", "fehlende Blütenhülle"),
                            ("lip", "Lippenblüte"),
                            ("sch", "Schmetterlingsblüte"),
                            ("zun", "Zungenblüte"),
                            ("str", "strahlende Randblüten"),
                        ],
                        max_length=3,
                        verbose_name="Blütenstandtyp",
                    ),
                ),
                (
                    "chalice",
                    models.CharField(
                        choices=[("v", "verwachsen"), ("u", "unverwachsen")],
                        max_length=1,
                        verbose_name="Kelchblätter",
                    ),
                ),
                (
                    "ch_type",
                    models.CharField(
                        choices=[
                            ("fre", "freiblättrig"),
                            ("ver", "verwachsenblättrig"),
                            ("2-z", "2-zähnig"),
                            ("3-z", "3-zähnig"),
                            ("4-z", "4-zähnig"),
                            ("5-z", "5-zähnig"),
                            ("2-l", "2-lappig"),
                            ("3-l", "3-lappig"),
                            ("4-l", "4-lappig"),
                            ("5-l", "5-lappig"),
                            ("2-s", "2-spaltig"),
                            ("3-s", "3-spaltig"),
                            ("4-s", "4-spaltig"),
                            ("5-s", "5-spaltig"),
                            ("2-t", "2-teilig"),
                            ("3-t", "3-teilig"),
                            ("4-t", "4-teilig"),
                            ("5-t", "5-teilig"),
                            ("zwe", "zweilippig"),
                        ],
                        max_length=3,
                        verbose_name="Verwachsungstyp",
                    ),
                ),
                (
                    "crown_color",
                    models.CharField(default="", max_length=100, verbose_name="Farbe"),
                ),
                (
                    "crown_ver",
                    models.CharField(
                        choices=[
                            ("v", "verwachsen"),
                            ("u", "unverwachsen"),
                            ("a", "am Grund verwachsen"),
                        ],
                        max_length=1,
                        verbose_name="Verwachsung der Kronblätter",
                    ),
                ),
                (
                    "crown_plate",
                    models.CharField(
                        default="", max_length=100, verbose_name="Kronblatt Platte"
                    ),
                ),
                (
                    "crown_lower",
                    models.CharField(
                        choices=[
                            ("fre", "freiblättrig"),
                            ("ver", "verwachsenblättrig"),
                            ("2-z", "2-zähnig"),
                            ("3-z", "3-zähnig"),
                            ("4-z", "4-zähnig"),
                            ("5-z", "5-zähnig"),
                            ("2-l", "2-lappig"),
                            ("3-l", "3-lappig"),
                            ("4-l", "4-lappig"),
                            ("5-l", "5-lappig"),
                            ("2-s", "2-spaltig"),
                            ("3-s", "3-spaltig"),
                            ("4-s", "4-spaltig"),
                            ("5-s", "5-spaltig"),
                            ("2-t", "2-teilig"),
                            ("3-t", "3-teilig"),
                            ("4-t", "4-teilig"),
                            ("5-t", "5-teilig"),
                            ("zwe", "zweilippig"),
                        ],
                        max_length=3,
                        verbose_name="Kronblatt Unterlippe",
                    ),
                ),
                (
                    "crown_out",
                    models.CharField(
                        default="",
                        max_length=100,
                        verbose_name="Ausstülpung der Unterlippe",
                    ),
                ),
                (
                    "dust_cnt",
                    models.CharField(
                        default="", max_length=100, verbose_name="Staubblatt Anzahl"
                    ),
                ),
                (
                    "dust_len",
                    models.CharField(
                        default="", max_length=100, verbose_name="Staubblatt Länge"
                    ),
                ),
                (
                    "dust_color",
                    models.CharField(
                        default="", max_length=100, verbose_name="Staubbeutel Farbe"
                    ),
                ),
                (
                    "dust_pipe",
                    models.CharField(
                        default="", max_length=100, verbose_name="Staubfadenröhre"
                    ),
                ),
                (
                    "fruit_cnt",
                    models.CharField(
                        default="", max_length=100, verbose_name="Fruchtknoten Anzahl"
                    ),
                ),
                (
                    "fruit_stand",
                    models.CharField(
                        choices=[
                            ("hy", "hypogyn/oberständig"),
                            ("eh", "epihypogyn/halboberständig"),
                            ("pe", "perigyn/mittelständig"),
                            ("he", "hemiepigyn/halbunterständig"),
                            ("ep", "epigyn/unterständig"),
                        ],
                        max_length=2,
                        verbose_name="Frucht Ständigkeit",
                    ),
                ),
                (
                    "fruit_build",
                    models.CharField(
                        choices=[
                            ("mo", "monokarp"),
                            ("ap", "apokarp/chorikarp"),
                            ("cs", "coeno-synkarp"),
                            ("cp", "coeno-parakarp"),
                        ],
                        max_length=2,
                        verbose_name="Bau des Gynoeceums",
                    ),
                ),
                (
                    "fruit_scar",
                    models.CharField(
                        default="", max_length=100, verbose_name="Narben pro Griffel"
                    ),
                ),
                (
                    "griffel_stand",
                    models.CharField(
                        choices=[
                            ("en", "endständig"),
                            ("se", "seitenständig"),
                            ("gr", "grundständig"),
                            ("gy", "gynobasisch"),
                        ],
                        max_length=2,
                        verbose_name="Ständigkeit des Griffels",
                    ),
                ),
                (
                    "griffel_sub",
                    models.BooleanField(
                        default=False, verbose_name="Ständigkeit des Griffels ist sub-"
                    ),
                ),
                (
                    "spec_sporn",
                    models.CharField(
                        choices=[
                            ("ro", "röhrig"),
                            ("ke", "keulig"),
                            ("gl", "glockig"),
                            ("tr", "trichterförmig"),
                            ("be", "becherförmig"),
                            ("na", "napfförmig"),
                            ("ku", "kugelig"),
                            ("au", "aufgeblasen"),
                            ("kr", "krugförmig"),
                            ("ra", "radförmig"),
                            ("st", "stielförmig"),
                            ("zu", "zungenförmig"),
                            ("ba", "bauchig"),
                            ("as", "ausgesackt"),
                            ("gr", "gespornt"),
                        ],
                        max_length=2,
                        verbose_name="Sporn",
                    ),
                ),
                (
                    "spec_hon",
                    models.CharField(
                        default="",
                        max_length=100,
                        verbose_name="Honigdrüsen / Nektarien",
                    ),
                ),
                (
                    "sec_out",
                    models.CharField(
                        default="", max_length=100, verbose_name="Außenkelch"
                    ),
                ),
                (
                    "spec_pol",
                    models.CharField(
                        default="", max_length=100, verbose_name="Griffelpolster"
                    ),
                ),
                (
                    "spec_pipe",
                    models.CharField(
                        default="", max_length=100, verbose_name="Schlauch"
                    ),
                ),
                (
                    "grann_top",
                    models.CharField(
                        choices=[("sp", "Spitzengranne"), ("un", "unbegrannt")],
                        max_length=2,
                        verbose_name="Granne der Deckspelze",
                    ),
                ),
                (
                    "grann_form",
                    models.CharField(
                        choices=[
                            ("gr", "gerade"),
                            ("gk", "gekniet"),
                            ("gd", "gedreht"),
                        ],
                        max_length=2,
                        verbose_name="Form der Granne",
                    ),
                ),
                (
                    "cons_top",
                    models.CharField(
                        default="",
                        max_length=100,
                        verbose_name="Konsistenz der Deckspelze",
                    ),
                ),
                (
                    "gull_spel",
                    models.CharField(
                        default="", max_length=100, verbose_name="Hüllspelzen"
                    ),
                ),
                (
                    "blos",
                    models.CharField(default="", max_length=100, verbose_name="Blütig"),
                ),
                (
                    "straw_ground",
                    models.CharField(
                        choices=[
                            ("ge", "gestielt"),
                            ("si", "sitzend / ungestielt"),
                            ("st", "stengelumfassend"),
                            ("ha", "halbstengelumfassend"),
                            ("du", "durchwachsen"),
                            ("ve", "verwachsen"),
                            ("sc", "scheidig verwachsen"),
                            ("he", "herablaufend"),
                            ("re", "reitend"),
                            ("hi", "hinfällig"),
                        ],
                        max_length=2,
                        verbose_name="Ansatz an Halm",
                    ),
                ),
                (
                    "order",
                    models.CharField(
                        default="", max_length=100, verbose_name="Ähren pro Ährchen "
                    ),
                ),
                (
                    "aer_per_aer",
                    models.CharField(
                        default="", max_length=100, verbose_name="Anordnung "
                    ),
                ),
                (
                    "aer_per_ab",
                    models.CharField(
                        default="", max_length=100, verbose_name="Ährchen pro Absatz"
                    ),
                ),
                (
                    "plant",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="blossom",
                        to="dive_content.Plant",
                        verbose_name="Pflanze",
                    ),
                ),
            ],
        ),
    ]
