# Generated by Django 3.0.5 on 2020-04-07 17:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("dive_content", "0007_add_blanks_to_choice_fields"),
    ]

    operations = [
        migrations.AlterField(
            model_name="blossom",
            name="cnt",
            field=models.IntegerField(
                blank=True,
                choices=[(3, 3), (4, 4), (5, 5)],
                null=True,
                verbose_name="Zähligkeit",
            ),
        ),
        migrations.AlterField(
            model_name="leaf",
            name="cnt_germ",
            field=models.IntegerField(
                blank=True,
                choices=[(1, 1), (2, 2)],
                null=True,
                verbose_name="Anzahl der Keimblätter",
            ),
        ),
    ]
