# Generated by Django 3.0.5 on 2020-04-08 14:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("dive_content", "0008_add_blank_and_null_to_integer_fields"),
    ]

    operations = [
        migrations.AlterField(
            model_name="blossom",
            name="aer_per_ab",
            field=models.CharField(
                blank=True, max_length=100, verbose_name="Ährchen pro Absatz"
            ),
        ),
        migrations.AlterField(
            model_name="blossom",
            name="aer_per_aer",
            field=models.CharField(
                blank=True, max_length=100, verbose_name="Anordnung "
            ),
        ),
        migrations.AlterField(
            model_name="blossom",
            name="bl_cnt",
            field=models.CharField(
                blank=True, max_length=100, verbose_name="Blüten pro Blütenstand"
            ),
        ),
        migrations.AlterField(
            model_name="blossom",
            name="blos",
            field=models.CharField(blank=True, max_length=100, verbose_name="Blütig"),
        ),
        migrations.AlterField(
            model_name="blossom",
            name="cons_top",
            field=models.CharField(
                blank=True, max_length=100, verbose_name="Konsistenz der Deckspelze"
            ),
        ),
        migrations.AlterField(
            model_name="blossom",
            name="crown_color",
            field=models.CharField(blank=True, max_length=100, verbose_name="Farbe"),
        ),
        migrations.AlterField(
            model_name="blossom",
            name="crown_out",
            field=models.CharField(
                blank=True, max_length=100, verbose_name="Ausstülpung der Unterlippe"
            ),
        ),
        migrations.AlterField(
            model_name="blossom",
            name="crown_plate",
            field=models.CharField(
                blank=True, max_length=100, verbose_name="Kronblatt Platte"
            ),
        ),
        migrations.AlterField(
            model_name="blossom",
            name="dust_cnt",
            field=models.CharField(
                blank=True, max_length=100, verbose_name="Staubblatt Anzahl"
            ),
        ),
        migrations.AlterField(
            model_name="blossom",
            name="dust_color",
            field=models.CharField(
                blank=True, max_length=100, verbose_name="Staubbeutel Farbe"
            ),
        ),
        migrations.AlterField(
            model_name="blossom",
            name="dust_len",
            field=models.CharField(
                blank=True, max_length=100, verbose_name="Staubblatt Länge"
            ),
        ),
        migrations.AlterField(
            model_name="blossom",
            name="dust_pipe",
            field=models.CharField(
                blank=True, max_length=100, verbose_name="Staubfadenröhre"
            ),
        ),
        migrations.AlterField(
            model_name="blossom",
            name="fruit_cnt",
            field=models.CharField(
                blank=True, max_length=100, verbose_name="Fruchtknoten Anzahl"
            ),
        ),
        migrations.AlterField(
            model_name="blossom",
            name="fruit_scar",
            field=models.CharField(
                blank=True, max_length=100, verbose_name="Narben pro Griffel"
            ),
        ),
        migrations.AlterField(
            model_name="blossom",
            name="gull_spel",
            field=models.CharField(
                blank=True, max_length=100, verbose_name="Hüllspelzen"
            ),
        ),
        migrations.AlterField(
            model_name="blossom",
            name="order",
            field=models.CharField(
                blank=True, max_length=100, verbose_name="Ähren pro Ährchen "
            ),
        ),
        migrations.AlterField(
            model_name="blossom",
            name="sec_out",
            field=models.CharField(
                blank=True, max_length=100, verbose_name="Außenkelch"
            ),
        ),
        migrations.AlterField(
            model_name="blossom",
            name="spec_hon",
            field=models.CharField(
                blank=True, max_length=100, verbose_name="Honigdrüsen / Nektarien"
            ),
        ),
        migrations.AlterField(
            model_name="blossom",
            name="spec_pipe",
            field=models.CharField(blank=True, max_length=100, verbose_name="Schlauch"),
        ),
        migrations.AlterField(
            model_name="blossom",
            name="spec_pol",
            field=models.CharField(
                blank=True, max_length=100, verbose_name="Griffelpolster"
            ),
        ),
        migrations.AlterField(
            model_name="fruit",
            name="cnt",
            field=models.CharField(
                blank=True, max_length=200, verbose_name="Samenzahl"
            ),
        ),
        migrations.AlterField(
            model_name="fruit",
            name="form",
            field=models.CharField(blank=True, max_length=200, verbose_name="Form"),
        ),
        migrations.AlterField(
            model_name="fruit",
            name="wings",
            field=models.CharField(
                blank=True,
                help_text='Gib "Nicht vorhanden" ein falls es wichtig ist, dass dieses Merkmal nicht ausgeprägt ist.',
                max_length=200,
                verbose_name="Beflügelung",
            ),
        ),
        migrations.AlterField(
            model_name="fruit",
            name="wings_spec",
            field=models.CharField(
                blank=True, max_length=200, verbose_name="Beflügelung Besonderheit"
            ),
        ),
        migrations.AlterField(
            model_name="leaf",
            name="count",
            field=models.CharField(
                blank=True, max_length=200, verbose_name="Anzahl Blättchen"
            ),
        ),
        migrations.AlterField(
            model_name="leaf",
            name="sheath",
            field=models.CharField(
                blank=True,
                help_text='Gib "Nicht vorhanden" ein falls es wichtig ist, dass dieses Merkmal nicht ausgeprägt ist.',
                max_length=100,
                verbose_name="Blattscheide",
            ),
        ),
        migrations.AlterField(
            model_name="leaf",
            name="specialty",
            field=models.CharField(
                blank=True,
                help_text='Gib "Nicht vorhanden" ein falls es wichtig ist, dass dieses Merkmal nicht ausgeprägt ist.',
                max_length=200,
                verbose_name="Besondere Merkmale",
            ),
        ),
        migrations.AlterField(
            model_name="sprout",
            name="blade",
            field=models.CharField(blank=True, max_length=200, verbose_name="Halm"),
        ),
        migrations.AlterField(
            model_name="sprout",
            name="cluster",
            field=models.CharField(blank=True, max_length=200, verbose_name="Horst"),
        ),
    ]
