# Generated by Django 3.0.5 on 2020-04-10 19:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("dive_content", "0012_create_spr_structure_field"),
    ]

    operations = [
        migrations.AlterField(
            model_name="leaf",
            name="arr_cuts",
            field=models.CharField(
                blank=True,
                choices=[
                    ("han", "handförmig/fingerförmig"),
                    ("hgl", "handförmig gelappt"),
                    ("hgt", "handförmig geteilt"),
                    ("hgs", "handförmig geschnitten"),
                    ("gef", "gefingert"),
                    ("fie", "fiederförmig/fiederig"),
                    ("fil", "fiederlappig"),
                    ("fip", "fiederspaltig"),
                    ("fit", "fiederteilig"),
                    ("fis", "fiederschnittig"),
                    ("paa", "paarig gefiedert"),
                    ("unp", "unpaarig gefiedert"),
                    ("unf", "unterbrochen fiederschnittig"),
                    ("ung", "unterbrochen gefiedert"),
                    ("dog", "doppelt gefiedert"),
                    ("meh", "mehrfach gefiedert"),
                    ("dre", "dreizählig"),
                    ("dod", "doppelt dreizählig"),
                    ("lei", "leierförmig"),
                    ("sch", "schrotsägeförmig"),
                    ("kam", "kammförmig"),
                    ("fug", "fußförmig geschnitten"),
                    ("fuz", "fußförmig zusammengesetzt"),
                ],
                max_length=3,
                verbose_name="Anordnung der Spreite",
            ),
        ),
        migrations.AlterField(
            model_name="leaf",
            name="form",
            field=models.CharField(
                blank=True,
                choices=[
                    ("kre", "kreisrund"),
                    ("run", "rundlich"),
                    ("ell", "elliptisch"),
                    ("eif", "eiförmig"),
                    ("ver", "verkehrteiförmig"),
                    ("spa", "spatelförmig/spatelig"),
                    ("len", "lanzettlich"),
                    ("eil", "eilanzettlich"),
                    ("lae", "länglich"),
                    ("lin", "linealisch/lineal"),
                    ("nad", "nadelförmig"),
                    ("pfr", "pfriemlich"),
                    ("bor", "borstenförmig/borstlich"),
                    ("fad", "fadenförmig/fädlich"),
                    ("bin", "binsenartig"),
                    ("roe", "röhrig"),
                    ("ser", "schwertförmig"),
                    ("dre", "dreieckig"),
                    ("kei", "keilförmig"),
                    ("rau", "rautenförmig/rhombisch"),
                    ("her", "herzförmig"),
                    ("vhe", "verkehrtherzförmig"),
                    ("nie", "nierenförmig"),
                    ("pfe", "pfeilförmig"),
                    ("spi", "spießförmig"),
                    ("gei", "geigenförmig"),
                    ("sup", "schuppenförmig"),
                    ("sil", "schildförmig"),
                ],
                max_length=3,
                verbose_name="Gestalt der Spreite",
            ),
        ),
    ]
