# Generated by Django 3.0.8 on 2020-07-26 17:41

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dive_content', '0017_auto_20200726_1845'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='sprout',
            options={'verbose_name': 'Spross', 'verbose_name_plural': 'Spross'},
        ),
        migrations.AddField(
            model_name='plant',
            name='alt_trivial_name',
            field=models.CharField(default='', max_length=500, verbose_name='Liste alternativer Trivialnamen'),
        ),
        migrations.AlterField(
            model_name='blossom',
            name='aer_per_ab',
            field=models.CharField(blank=True, max_length=100, verbose_name='Ährchen pro Absatz der Ährenachse'),
        ),
        migrations.AlterField(
            model_name='blossom',
            name='aer_per_aer',
            field=models.CharField(blank=True, max_length=100, verbose_name='Anordnung der Ährchen'),
        ),
        migrations.AlterField(
            model_name='blossom',
            name='blos',
            field=models.CharField(blank=True, max_length=100, verbose_name='Blütigkeit des Ährchens'),
        ),
        migrations.AlterField(
            model_name='blossom',
            name='crown_color',
            field=models.CharField(blank=True, max_length=100, verbose_name='Kronblattfarbe'),
        ),
        migrations.AlterField(
            model_name='blossom',
            name='fruit_stand',
            field=models.CharField(blank=True, choices=[('hy', 'hypogyn/oberständig'), ('eh', 'epihypogyn/halboberständig'), ('pe', 'perigyn/mittelständig'), ('he', 'hemiepigyn/halbunterständig'), ('ep', 'epigyn/unterständig')], max_length=2, verbose_name='Ständigkeit des Fruchtknotens'),
        ),
        migrations.AlterField(
            model_name='blossom',
            name='hull',
            field=models.CharField(blank=True, choices=[('dop', 'doppelte Blütenhülle (Kalyx + Corolla)'), ('ein', 'einfache Blütenhülle (Perigon)'), ('feh', 'fehlende Blütenhülle'), ('lip', 'Lippenblüte'), ('sch', 'Schmetterlingsblüte'), ('zun', 'Zungenblüte'), ('str', 'strahlende Randblüten')], max_length=3, verbose_name='Blütenhülle'),
        ),
        migrations.AlterField(
            model_name='blossom',
            name='order',
            field=models.CharField(blank=True, max_length=100, verbose_name='Ährchen pro Ähre'),
        ),
        migrations.AlterField(
            model_name='blossom',
            name='parting',
            field=models.CharField(blank=True, choices=[('gan', 'ganz/ungeteilt'), ('gel', 'gelappt'), ('gsp', 'gespalten'), ('get', 'geteilt'), ('ges', 'geschnitten'), ('han', 'handförmig/fingerförmig'), ('hgl', 'handförmig gelappt'), ('hgt', 'handförmig geteilt'), ('hgs', 'handförmig geschnitten'), ('gef', 'gefingert'), ('fie', 'fiederförmig/fiederig'), ('fil', 'fiederlappig'), ('fsp', 'fiederspaltig'), ('fit', 'fiederteilig'), ('fis', 'fiederschnittig'), ('paf', 'paarig gefiedert'), ('upf', 'unpaarig gefiedert'), ('unf', 'unterbrochen fiederschnittig'), ('ung', 'unterbrochen gefiedert'), ('dop', 'doppelt gefiedert'), ('meh', 'mehrfach gefiedert'), ('dre', 'dreizählig'), ('dod', 'doppelt dreizählig'), ('lei', 'leierförmig'), ('sch', 'schrotsägeförmig'), ('kam', 'kammförmig'), ('fug', 'fußförmig geschnitten'), ('fuz', 'fußförmig zusammengesetzt'), ('non', 'nicht vorhanden')], max_length=3, verbose_name='Tragblattspreite'),
        ),
        migrations.AlterField(
            model_name='blossom',
            name='type',
            field=models.CharField(blank=True, choices=[('ein', 'einzeln'), ('tra', 'Traube'), ('ris', 'Rispe'), ('ebe', 'Ebenstrauß/Corymbus'), ('sct', 'Schirmtraube'), ('scr', 'Schirmrispe'), ('spi', 'Spirre/Trichterrispe'), ('aer', 'Ähre'), ('kol', 'Kolben'), ('kae', 'Kätzchen'), ('zap', 'Zapfen'), ('dol', 'Dolde'), ('dod', 'Doppeldolde'), ('kop', 'Kopf'), ('koc', 'Köpfchen'), ('kor', 'Korb'), ('krc', 'Körbchen'), ('zym', 'Zyme'), ('ple', 'Pleiochasium'), ('dic', 'Dichasium'), ('mon', 'Monochasium'), ('wic', 'Wickel'), ('dow', 'Doppelwickel'), ('scq', 'Scheinquirl'), ('bue', 'Büschel'), ('kna', 'Knäuel'), ('thy', 'Thyrse'), ('scd', 'Scheindolde/Trugdolde'), ('scb', 'Scheinblüte/Pseudanthium')], max_length=3, verbose_name='Blütenstandsform'),
        ),
        migrations.AlterField(
            model_name='leaf',
            name='leaflets',
            field=models.CharField(blank=True, choices=[('dor', 'dornig'), ('gan', 'ganzrandig'), ('ges', 'gesägt'), ('dop', 'doppelt gesägt'), ('rue', 'rückwärts gesägt'), ('gez', 'gezähnt'), ('gzt', 'gezähnelt'), ('gef', 'gefranst'), ('gek', 'gekerbt'), ('geb', 'gebuchtet'), ('ges', 'geschweift'), ('bew', 'bewimpert'), ('vor', 'vorwärts rauh'), ('rra', 'rückwärts rauh')], max_length=3, verbose_name='Spreiten-/Blättchenrand'),
        ),
        migrations.AlterField(
            model_name='leaf',
            name='sp_top',
            field=models.CharField(blank=True, choices=[('abg', 'abgerundet'), ('ges', 'gestzutzt'), ('stu', 'stumpf'), ('spi', 'spitz'), ('zug', 'zugespitzt'), ('beg', 'begrannt'), ('sta', 'stachelspitze'), ('haa', 'haarspitzig'), ('bes', 'bespitzt'), ('aus', 'ausgerandet')], max_length=3, verbose_name='Spreitenspitze'),
        ),
        migrations.AlterField(
            model_name='leaf',
            name='spr_whole',
            field=models.CharField(blank=True, choices=[('ein', 'einfach'), ('zus', 'zusammengesetzt')], max_length=3, verbose_name='Aufteilung der Blattspreite'),
        ),
        migrations.AlterField(
            model_name='leaf',
            name='sur_texture',
            field=models.CharField(blank=True, choices=[('gla', 'glatt'), ('run', 'runzelig'), ('rau', 'rauh'), ('vra', 'vorwärts rauh'), ('ber', 'bereift'), ('bes', 'bestäubt/bemehlt'), ('pap', 'papillös'), ('pun', 'punktiert'), ('swi', 'schwielig'), ('kah', 'kahl'), ('ver', 'verkahlend'), ('fla', 'flaumhaarig/weichhaarig'), ('sei', 'seidenhaarig'), ('spi', 'spinnwebig'), ('flo', 'flockig'), ('sam', 'samthaarig'), ('fil', 'filzig'), ('wol', 'wollig'), ('zot', 'zottig'), ('rah', 'rauhaarig'), ('ste', 'steifhaarig'), ('gew', 'gewimpert'), ('dru', 'drüsenhaarig'), ('ste', 'sternhaarig'), ('sdh', 'schildhaarig'), ('sup', 'schuppenhaarig/schuppig'), ('sue', 'schülferig'), ('bae', 'bärtig'), ('ach', 'achselbärtig'), ('nac', 'nackt')], max_length=3, verbose_name='Blattoberfläche'),
        ),
        migrations.AlterField(
            model_name='plant',
            name='ground',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(choices=[('rei', 'nährstoffreich'), ('arm', 'nährstoffarm'), ('leh', 'lehmig'), ('tor', 'torfig'), ('san', 'sandig'), ('ste', 'steinig/felsig')], max_length=3, verbose_name='Untergrund'), blank=True, size=None, verbose_name='Untergrund'),
        ),
        migrations.AlterField(
            model_name='sprout',
            name='diam',
            field=models.CharField(blank=True, choices=[('sti', 'stielrund'), ('hal', 'halbstielrund'), ('zus', 'zusammengedrückt'), ('zwe', 'zweischneidig'), ('kan', 'kantig'), ('stu', 'stumpfkantig'), ('ger', 'gerieft /gerillt'), ('gef', 'gefurcht'), ('kan', 'kantig gefurcht /scharfkantig'), ('gri', 'gerippt'), ('gfl', 'geflügelt'), ('kno', 'knotig')], max_length=3, verbose_name='Querschnitt'),
        ),
        migrations.AlterField(
            model_name='sprout',
            name='pos',
            field=models.CharField(blank=True, choices=[('auf', 'aufrecht'), ('aua', 'aufrecht-abstehend'), ('abs', 'abstehend'), ('spa', 'sparrig'), ('zur', 'zurückgeschlagen'), ('lie', 'liegend'), ('kri', 'kriechend'), ('aus', 'aufsteigend/aufstrebend'), ('gek', 'gekniet'), ('ueb', 'übergebogen'), ('nic', 'nickend'), ('hae', 'hängend'), ('flu', 'flutend'), ('Ran', 'Rankenpflanze'), ('Win', 'Windepflanze'), ('Spr', 'Spreizklimmer'), ('Wur', 'Wurzelkletterer'), ('hor', 'horstig'), ('loc', 'lockerrasig')], max_length=3, verbose_name='Wuchsorientierung'),
        ),
        migrations.AlterField(
            model_name='sprout',
            name='sur_texture',
            field=models.CharField(blank=True, choices=[('gla', 'glatt'), ('run', 'runzelig'), ('rau', 'rauh'), ('vra', 'vorwärts rauh'), ('ber', 'bereift'), ('bes', 'bestäubt/bemehlt'), ('pap', 'papillös'), ('pun', 'punktiert'), ('swi', 'schwielig'), ('kah', 'kahl'), ('ver', 'verkahlend'), ('fla', 'flaumhaarig/weichhaarig'), ('sei', 'seidenhaarig'), ('spi', 'spinnwebig'), ('flo', 'flockig'), ('sam', 'samthaarig'), ('fil', 'filzig'), ('wol', 'wollig'), ('zot', 'zottig'), ('rah', 'rauhaarig'), ('ste', 'steifhaarig'), ('gew', 'gewimpert'), ('dru', 'drüsenhaarig'), ('ste', 'sternhaarig'), ('sdh', 'schildhaarig'), ('sup', 'schuppenhaarig/schuppig'), ('sue', 'schülferig'), ('bae', 'bärtig'), ('ach', 'achselbärtig'), ('nac', 'nackt')], max_length=3, verbose_name='Sprossoberfläche'),
        ),
    ]
