# Generated by Django 3.0.8 on 2020-07-06 15:04

from django.db import migrations, models
import django.db.models.deletion

class Migration(migrations.Migration):

    dependencies = [
        ('dive_content', '0018_auto_20200706_1531'),
    ]

    operations = [
        migrations.AlterField(
            model_name="plant",
            name="systematics",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.DO_NOTHING,
                related_name="profiles",
                to="content.TreeNode",
                verbose_name="Steckbrief-Ebene",
            )
        )
    ]
