# Generated by Django 3.0.8 on 2021-02-16 14:30
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("content", "0001_create_tree_node_model"),
        ("dive_content", "0023_correct_typo_in_sp_top_field"),
    ]

    operations = [
        migrations.AlterField(
            model_name="plant",
            name="systematics",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.DO_NOTHING,
                related_name="systematics",
                to="content.TreeNode",
                verbose_name="Steckbrief-Ebene",
            ),
        ),
    ]
