# Generated by Django 3.0.8 on 2021-02-16 16:06

from django.db import migrations


def populate_tree_node_with_systematics(apps, schema_editor):
    """
    Populate tree_node fields with systematics values.
    """
    Plant = apps.get_model("dive_content", "Plant")

    for obj in Plant.objects.all():
        obj.tree_node = obj.systematics
        obj.save()


def populate_systematics_with_tree_node(apps, schema_editor):
    """
    Populate systematics fields with tree_node values.
    """
    Plant = apps.get_model("dive_content", "Plant")

    for obj in Plant.objects.all():
        obj.systematics = obj.tree_node
        obj.save()


class Migration(migrations.Migration):

    dependencies = [
        ("dive_content", "0025_add_plant_tree_node"),
    ]

    operations = [
        migrations.RunPython(
            populate_tree_node_with_systematics, populate_systematics_with_tree_node
        ),
    ]
