# Generated by Django 3.0.8 on 2021-02-16 16:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("dive_content", "0026_populate_plant_tree_node"),
    ]

    operations = [
        migrations.RemoveField(model_name="plant", name="systematics",),
    ]
