# Generated by Django 3.0.8 on 2021-03-01 13:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("dive_content", "0028_alter_plant_bloom"),
    ]

    operations = [
        migrations.RenameField(
            model_name="plant", old_name="facts_to_know", new_name="short_description",
        ),
    ]
