# Generated by Django 3.0.8 on 2021-03-03 12:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("dive_content", "0031_create_blossom_season"),
    ]

    operations = [
        migrations.AlterField(
            model_name="blossom",
            name="griffel_sub",
            field=models.CharField(
                blank=True,
                choices=[
                    ("end", "subendständig"),
                    ("sei", "subseitenständig"),
                    ("gru", "subgrundständig"),
                    ("gyn", "subgynobasisch"),
                ],
                max_length=3,
                verbose_name="Ständigkeit des Griffels ist sub-",
            ),
        ),
    ]
