# Generated by Django 3.0.8 on 2021-03-03 12:50

from django.db import migrations


def populate_blossom_season_with_plant_bloom(apps, schema_editor):
    """
    Populate Blossom model season fields with Plant model bloom values.
    """
    Plant = apps.get_model("dive_content", "Plant")
    Blossom = apps.get_model("dive_content", "Blossom")

    for obj in (
        Plant.objects.exclude(bloom="").exclude(bloom="0").select_related("blossom")
    ):
        try:
            obj.blossom.season = obj.bloom
            obj.blossom.save()
        except Blossom.DoesNotExist:
            Blossom.objects.create(plant=obj, season=obj.bloom)


def populate_plant_bloom_with_blossom_season(apps, schema_editor):
    """
    Populate Plant model bloom fields with Blossom model season values.
    """
    Blossom = apps.get_model("dive_content", "Blossom")

    for obj in Blossom.objects.exclude(season="").select_related("plant"):
        obj.plant.bloom = obj.season
        obj.plant.save()


class Migration(migrations.Migration):

    dependencies = [
        ("dive_content", "0032_alter_blossom_griffel_sub"),
    ]

    operations = [
        migrations.RunPython(
            populate_blossom_season_with_plant_bloom,
            populate_plant_bloom_with_blossom_season,
        ),
    ]
