# Generated by Django 3.0.8 on 2021-03-03 13:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("dive_content", "0033_populate_blossom_season"),
    ]

    operations = [
        migrations.RemoveField(model_name="plant", name="bloom",),
    ]
