# Generated by Django 3.0.8 on 2021-03-03 18:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("dive_content", "0034_remove_plant_bloom"),
    ]

    operations = [
        migrations.AddField(
            model_name="sprout",
            name="primary_root",
            field=models.CharField(
                blank=True,
                choices=[
                    ("erh", "erhalten"),
                    ("ers", "ersetzt durch sprossbürtige Wurzeln"),
                ],
                max_length=3,
                verbose_name="Primärwurzel",
            ),
        ),
    ]
