# Generated by Django 3.0.8 on 2021-03-03 19:08

from django.db import migrations


def populate_sprout_primary_root_with_plant_prime_root(apps, schema_editor):
    """
    Populate Sprout model primary_root fields with Plant model prime_root values.
    """
    Plant = apps.get_model("dive_content", "Plant")
    Sprout = apps.get_model("dive_content", "Sprout")

    for obj in Plant.objects.exclude(prime_root="").select_related("sprout"):
        try:
            obj.sprout.primary_root = obj.prime_root
            obj.sprout.save()
        except Sprout.DoesNotExist:
            Sprout.objects.create(plant=obj, primary_root=obj.prime_root)


def populate_plant_prime_root_with_sprout_primary_root(apps, schema_editor):
    """
    Populate Plant model prime_root fields with Sprout model primary_root values.
    """
    Sprout = apps.get_model("dive_content", "Sprout")

    for obj in Sprout.objects.exclude(primary_root="").select_related("plant"):
        obj.plant.prime_root = obj.primary_root
        obj.plant.save()


class Migration(migrations.Migration):

    dependencies = [
        ("dive_content", "0035_create_sprout_primary_root"),
    ]

    operations = [
        migrations.RunPython(
            populate_sprout_primary_root_with_plant_prime_root,
            populate_plant_prime_root_with_sprout_primary_root,
        ),
    ]
