# Generated by Django 3.0.8 on 2021-03-03 19:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("dive_content", "0036_populate_sprout_primary_root"),
    ]

    operations = [
        migrations.RemoveField(model_name="plant", name="prime_root",),
    ]
