# Generated by Django 3.0.8 on 2021-03-03 19:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("dive_content", "0037_remove_plant_prime_root"),
    ]

    operations = [
        migrations.RemoveField(model_name="plant", name="nodule",),
    ]
