# Generated by Django 3.0.8 on 2021-03-03 19:41

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("dive_content", "0038_remove_plant_nodule"),
    ]

    operations = [
        migrations.AlterField(
            model_name="plant",
            name="habitat",
            field=django.contrib.postgres.fields.ArrayField(
                base_field=models.CharField(
                    choices=[
                        ("sch", "Schlammfluren"),
                        ("roe", "Röhrichte"),
                        ("sae", "Säume"),
                        ("sta", "Staudenfluren"),
                        ("gru", "Grünland und Zwergstrauchheiden"),
                        ("rud", "Ruderalvegetation"),
                        ("aec", "Äcker"),
                        ("wei", "Weinberge"),
                        ("int", "Intensivgrünland"),
                        ("par", "Parks"),
                        ("gae", "Gärten"),
                        ("tri", "Trittpflanzengesellschaften"),
                        ("fel", "Felsbiotope"),
                        ("aue", "Auenwälder"),
                        ("geb", "Gebüsche"),
                        ("ger", "Geröll"),
                        ("ext", "Extensivgrünland oder natürlicher Rasen"),
                        ("wae", "Wälder"),
                        ("ufe", "Ufer"),
                    ],
                    max_length=3,
                    verbose_name="Habitat",
                ),
                blank=True,
                size=None,
            ),
        ),
    ]
