# Generated by Django 3.0.8 on 2021-03-03 20:01

import django.contrib.postgres.fields
from django.db import migrations, models


def remove_values_from_plant_ground(apps, schema_editor):
    """
    Remove 'rei' and 'arm' values from Plant model ground array field.
    """
    Plant = apps.get_model("dive_content", "Plant")

    for obj in Plant.objects.filter(ground__overlap=["rei", "arm"]):
        if "rei" in obj.ground:
            obj.ground.remove("rei")
        if "arm" in obj.ground:
            obj.ground.remove("arm")
        obj.save()


class Migration(migrations.Migration):

    dependencies = [
        ("dive_content", "0039_alter_plant_habitat"),
    ]

    operations = [
        migrations.RunPython(
            remove_values_from_plant_ground, migrations.RunPython.noop,
        ),
        migrations.AlterField(
            model_name="plant",
            name="ground",
            field=django.contrib.postgres.fields.ArrayField(
                base_field=models.CharField(
                    choices=[
                        ("leh", "lehmig"),
                        ("tor", "torfig"),
                        ("san", "sandig"),
                        ("ste", "steinig/felsig"),
                    ],
                    max_length=3,
                    verbose_name="Untergrund",
                ),
                blank=True,
                size=None,
            ),
        ),
    ]
