# Generated by Django 3.0.8 on 2021-03-04 13:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("dive_content", "0040_alter_plant_ground"),
    ]

    operations = [
        migrations.AddField(
            model_name="plant",
            name="life_form",
            field=models.CharField(
                blank=True,
                choices=[
                    ("pha", "Phanerophyt"),
                    ("cha", "Chamaephyt"),
                    ("hem", "Hemikryptophyt"),
                    ("kry", "Kryptophyt"),
                    ("the", "Therophyt"),
                ],
                max_length=3,
                verbose_name="Lebensform",
            ),
        ),
    ]
