# Generated by Django 3.0.8 on 2021-03-04 13:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("dive_content", "0041_create_plant_life_form"),
    ]

    operations = [
        migrations.AddField(
            model_name="plant",
            name="growth_form",
            field=models.CharField(
                blank=True,
                choices=[
                    ("bau", "Baum"),
                    ("str", "Strauch"),
                    ("stb", "Strauchbaum"),
                    ("zwe", "Zwergstrauch"),
                    ("lia", "Liane"),
                    ("kle", "Kletterpflanze"),
                    ("hal", "Halbstrauch"),
                    ("spa", "Spalierstrauch"),
                    ("krc", "krautiger Chemaephyt"),
                    ("geo", "Geophyt"),
                    ("hel", "Helophyt (Sumpfpflanze)"),
                    ("hyd", "Hydrophyt (Wasserpflanze)"),
                    ("tau", "Tauchpflanze"),
                    ("sch", "Schwimmpflanze"),
                ],
                max_length=3,
                verbose_name="Wuchsform",
            ),
        ),
    ]
