# Generated by Django 3.0.8 on 2021-03-04 14:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("dive_content", "0042_create_plant_growth_form"),
    ]

    operations = [
        migrations.AddField(
            model_name="plant",
            name="growth_height",
            field=models.CharField(
                blank=True,
                help_text="Bsp. 10-15 cm",
                max_length=100,
                verbose_name="Wuchshöhe",
            ),
        ),
    ]
