# Generated by Django 3.0.8 on 2021-03-04 15:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("dive_content", "0043_create_plant_growth_height"),
    ]

    operations = [
        migrations.AddField(
            model_name="plant",
            name="dispersal",
            field=models.CharField(
                blank=True,
                choices=[("sa", "Samenpflanze"), ("sp", "Sporenpflanze")],
                max_length=2,
                verbose_name="Ausbreitungsform",
            ),
        ),
    ]
