# Generated by Django 3.0.8 on 2021-03-04 15:24

from django.db import migrations


def populate_plant_dispersal_with_fruit_spread(apps, schema_editor):
    """
    Populate Plant model dispersal fields with Fruit model spread values.
    """
    Fruit = apps.get_model("dive_content", "Fruit")

    for obj in Fruit.objects.exclude(spread="").select_related("plant"):
        obj.plant.dispersal = obj.spread
        obj.plant.save()


def populate_fruit_spread_with_plant_dispersal(apps, schema_editor):
    """
    Populate Fruit model spread fields with Plant model dispersal values.
    """
    Plant = apps.get_model("dive_content", "Plant")
    Fruit = apps.get_model("dive_content", "Fruit")

    for obj in Plant.objects.exclude(dispersal="").select_related("fruit"):
        try:
            obj.fruit.spread = obj.dispersal
            obj.fruit.save()
        except Fruit.DoesNotExist:
            Fruit.objects.create(plant=obj, spread=obj.dispersal)


class Migration(migrations.Migration):

    dependencies = [
        ("dive_content", "0044_create_plant_dispersal"),
    ]

    operations = [
        migrations.RunPython(
            populate_plant_dispersal_with_fruit_spread,
            populate_fruit_spread_with_plant_dispersal,
        ),
    ]
