# Generated by Django 3.0.8 on 2021-03-04 15:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("dive_content", "0045_populate_plant_dispersal"),
    ]

    operations = [
        migrations.RemoveField(model_name="fruit", name="spread",),
    ]
