# Generated by Django 3.0.8 on 2021-03-05 10:09

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("dive_content", "0046_remove_fruit_spread"),
    ]

    operations = [
        migrations.AlterField(
            model_name="plant",
            name="ground",
            field=django.contrib.postgres.fields.ArrayField(
                base_field=models.CharField(
                    choices=[
                        ("leh", "lehmig"),
                        ("tor", "torfig"),
                        ("san", "sandig"),
                        ("ste", "steinig/felsig"),
                    ],
                    max_length=3,
                    verbose_name="Untergrund",
                ),
                blank=True,
                size=2,
            ),
        ),
    ]
