# Generated by Django 3.0.8 on 2021-03-07 08:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("dive_content", "0047_alter_plant_ground"),
    ]

    operations = [
        migrations.RemoveField(model_name="leaf", name="spr_structure",),
    ]
