# Generated by Django 3.0.8 on 2021-03-23 13:50

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("dive_content", "0047_alter_plant_ground"),
    ]

    operations = [
        migrations.AddField(
            model_name="leaf",
            name="attachment",
            field=django.contrib.postgres.fields.ArrayField(
                base_field=models.CharField(
                    choices=[
                        ("ges", "gestielt"),
                        ("sit", "sitzend/ungestielt"),
                        ("ste", "stengelumfassend"),
                        ("hal", "halbstengelumfassend"),
                        ("dur", "durchwachsen"),
                        ("ver", "verwachsen"),
                        ("sch", "scheidig verwachsen"),
                        ("her", "herablaufend"),
                        ("rei", "reitend"),
                        ("hin", "hinfällig"),
                    ],
                    max_length=3,
                    verbose_name="Anheftung (an Sprossachse)",
                ),
                blank=True,
                default=list,
                size=2,
            ),
        ),
        migrations.AddField(
            model_name="leaf",
            name="incision_depth",
            field=django.contrib.postgres.fields.ArrayField(
                base_field=models.CharField(
                    choices=[
                        ("gan", "ganz/ungeteilt"),
                        ("gel", "gelappt"),
                        ("gep", "gespalten"),
                        ("get", "geteilt"),
                        ("ges", "geschnitten"),
                        ("gef", "gefingert"),
                        ("zus", "zusammengesetzt"),
                        ("fis", "fiederschnittig"),
                        ("fie", "gefiedert"),
                    ],
                    max_length=3,
                    verbose_name="Einschnitttiefe",
                ),
                blank=True,
                default=list,
                size=2,
            ),
        ),
        migrations.AddField(
            model_name="leaf",
            name="blade_subdiv_shape",
            field=django.contrib.postgres.fields.ArrayField(
                base_field=models.CharField(
                    choices=[
                        ("han", "handförmig"),
                        ("gef", "gefingert"),
                        ("fif", "fiederförmig"),
                        ("fil", "fiederlappig"),
                        ("fip", "fiederspaltig"),
                        ("fit", "fiederteilig"),
                        ("fis", "fiederschnittig"),
                        ("paa", "paarig"),
                        ("unp", "unpaarig"),
                        ("unt", "unterbrochen"),
                        ("dop", "doppelt"),
                        ("meh", "mehrfach"),
                        ("dre", "dreizählig"),
                        ("dod", "doppelt dreizählig"),
                        ("lei", "leierförmig"),
                        ("sch", "schrotsägeförmig"),
                        ("kam", "kammförmig"),
                        ("fus", "fußförmig"),
                    ],
                    max_length=3,
                    verbose_name="Spreitengestalt (unterteiltes Blatt)",
                ),
                blank=True,
                default=list,
                size=2,
            ),
        ),
        migrations.AddField(
            model_name="leaf",
            name="blade_undiv_shape",
            field=django.contrib.postgres.fields.ArrayField(
                base_field=models.CharField(
                    choices=[
                        ("kre", "kreisrund"),
                        ("run", "rundlich"),
                        ("ell", "elliptisch"),
                        ("eif", "eiförmig"),
                        ("ver", "verkehrteiförmig"),
                        ("spa", "spatelförmig/spatelig"),
                        ("len", "lanzettlich"),
                        ("eil", "eilanzettlich"),
                        ("lae", "länglich"),
                        ("lin", "linealisch/lineal"),
                        ("nad", "nadelförmig"),
                        ("pfr", "pfriemlich"),
                        ("bor", "borstenförmig/borstlich"),
                        ("fad", "fadenförmig/fädlich"),
                        ("bin", "binsenartig"),
                        ("roe", "röhrig"),
                        ("ser", "schwertförmig"),
                        ("dre", "dreieckig"),
                        ("kei", "keilförmig"),
                        ("rau", "rautenförmig/rhombisch"),
                        ("her", "herzförmig"),
                        ("vhe", "verkehrtherzförmig"),
                        ("nie", "nierenförmig"),
                        ("pfe", "pfeilförmig"),
                        ("spi", "spießförmig"),
                        ("gei", "geigenförmig"),
                        ("sup", "schuppenförmig"),
                        ("sil", "schildförmig"),
                    ],
                    max_length=3,
                    verbose_name="Spreitengestalt (ungeteiltes Blatt)",
                ),
                blank=True,
                default=list,
                size=2,
            ),
        ),
        migrations.AddField(
            model_name="leaf",
            name="edge",
            field=django.contrib.postgres.fields.ArrayField(
                base_field=models.CharField(
                    choices=[
                        ("dor", "dornig"),
                        ("gan", "ganzrandig"),
                        ("ges", "gesägt"),
                        ("dop", "doppelt gesägt"),
                        ("rue", "rückwärts gesägt"),
                        ("gez", "gezähnt"),
                        ("gzt", "gezähnelt"),
                        ("gef", "gefranst"),
                        ("gek", "gekerbt"),
                        ("geb", "gebuchtet"),
                        ("gew", "geschweift"),
                        ("bew", "bewimpert"),
                        ("vor", "vorwärts rauh"),
                        ("rur", "rückwärts rauh"),
                    ],
                    max_length=3,
                    verbose_name="Spreiten-/Blättchenrand",
                ),
                blank=True,
                default=list,
                size=2,
            ),
        ),
        migrations.AddField(
            model_name="leaf",
            name="surface",
            field=django.contrib.postgres.fields.ArrayField(
                base_field=models.CharField(
                    choices=[
                        ("gla", "glatt"),
                        ("run", "runzelig"),
                        ("rau", "rauh"),
                        ("vra", "vorwärts rauh"),
                        ("ber", "bereift"),
                        ("bes", "bestäubt/bemehlt"),
                        ("pap", "papillös"),
                        ("pun", "punktiert"),
                        ("swi", "schwielig"),
                        ("kah", "kahl"),
                        ("ver", "verkahlend"),
                        ("fla", "flaumhaarig/weichhaarig"),
                        ("sei", "seidenhaarig"),
                        ("spi", "spinnwebig"),
                        ("flo", "flockig"),
                        ("sam", "samthaarig"),
                        ("fil", "filzig"),
                        ("wol", "wollig"),
                        ("zot", "zottig"),
                        ("rah", "rauhaarig"),
                        ("ste", "steifhaarig"),
                        ("gew", "gewimpert"),
                        ("dru", "drüsenhaarig"),
                        ("ste", "sternhaarig"),
                        ("sdh", "schildhaarig"),
                        ("sup", "schuppenhaarig/schuppig"),
                        ("sue", "schülferig"),
                        ("bae", "bärtig"),
                        ("ach", "achselbärtig"),
                        ("nac", "nackt"),
                    ],
                    max_length=3,
                    verbose_name="Blattoberfläche",
                ),
                blank=True,
                default=list,
                size=2,
            ),
        ),
        migrations.AddField(
            model_name="leaf",
            name="stipule_edge",
            field=django.contrib.postgres.fields.ArrayField(
                base_field=models.CharField(
                    choices=[
                        ("dor", "dornig"),
                        ("gan", "ganzrandig"),
                        ("ges", "gesägt"),
                        ("dop", "doppelt gesägt"),
                        ("rue", "rückwärts gesägt"),
                        ("gez", "gezähnt"),
                        ("gzt", "gezähnelt"),
                        ("gef", "gefranst"),
                        ("gek", "gekerbt"),
                        ("geb", "gebuchtet"),
                        ("gew", "geschweift"),
                        ("bew", "bewimpert"),
                        ("vor", "vorwärts rauh"),
                        ("rur", "rückwärts rauh"),
                    ],
                    max_length=3,
                    verbose_name="Nebenblattrand",
                ),
                blank=True,
                default=list,
                size=2,
            ),
        ),
        migrations.AddField(
            model_name="leaf",
            name="rosette",
            field=models.CharField(
                blank=True,
                choices=[
                    ("vor", "Grundblattrossette vorhanden"),
                    ("kei", "keine Grundblattrosette"),
                ],
                max_length=3,
                verbose_name="Grundblattrosette",
            ),
        ),
        migrations.AddField(
            model_name="leaf",
            name="leaf_comp_num",
            field=models.CharField(
                blank=True, max_length=10, verbose_name="Blattanzahl (zusg. Blätter)"
            ),
        ),
        migrations.AddField(
            model_name="leaf",
            name="incision_num",
            field=models.CharField(
                blank=True, max_length=10, verbose_name="Einschnittanzahl"
            ),
        ),
        migrations.AddField(
            model_name="leaf",
            name="leaflet_incision_num",
            field=models.CharField(
                blank=True, max_length=10, verbose_name="Einschnittanzahl (Blättchen)"
            ),
        ),
        migrations.AddField(
            model_name="leaf",
            name="leaflet_incision_add",
            field=models.CharField(
                blank=True, max_length=100, verbose_name="Einschnittzusatz (Blättchen)"
            ),
        ),
        migrations.AddField(
            model_name="leaf",
            name="leaflet_incision_depth",
            field=django.contrib.postgres.fields.ArrayField(
                base_field=models.CharField(
                    choices=[
                        ("gan", "ganz/ungeteilt"),
                        ("gel", "gelappt"),
                        ("gep", "gespalten"),
                        ("get", "geteilt"),
                        ("ges", "geschnitten"),
                        ("gef", "gefingert"),
                        ("zus", "zusammengesetzt"),
                        ("fis", "fiederschnittig"),
                        ("fie", "gefiedert"),
                    ],
                    max_length=3,
                    verbose_name="Einschnitttiefe (Blättchen)",
                ),
                blank=True,
                default=list,
                size=2,
            ),
        ),
        migrations.AddField(
            model_name="leaf",
            name="leaf_simple_num",
            field=models.CharField(
                blank=True, max_length=10, verbose_name="Blattanzahl (einf. Blätter)"
            ),
        ),
    ]
