# Generated by Django 3.0.8 on 2021-03-07 08:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("dive_content", "0048_remove_leaf_spr_structure"),
    ]

    operations = [
        migrations.RemoveField(model_name="leaf", name="count",),
    ]
