# Generated by Django 3.0.8 on 2021-03-23 13:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("dive_content", "0048_bulk_add_leaf"),
    ]

    operations = [
        migrations.RenameField(model_name="leaf", old_name="nerves", new_name="veins",),
        migrations.RenameField(
            model_name="leaf", old_name="spr_whole", new_name="division",
        ),
        migrations.RenameField(
            model_name="leaf", old_name="thick_flesh", new_name="succulence",
        ),
        migrations.RenameField(
            model_name="leaf", old_name="diam", new_name="cross_section",
        ),
        migrations.RenameField(
            model_name="leaf", old_name="pos_axis", new_name="arrangement",
        ),
        migrations.RenameField(
            model_name="leaf", old_name="sp_ground", new_name="base",
        ),
        migrations.RenameField(model_name="leaf", old_name="sp_top", new_name="apex",),
        migrations.RenameField(
            model_name="leaf", old_name="specialty", new_name="special_features",
        ),
        migrations.RenameField(
            model_name="leaf", old_name="cnt_germ", new_name="seed_leaf_num",
        ),
    ]
