# Generated by Django 3.0.8 on 2021-03-07 12:08

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("dive_content", "0049_remove_leaf_count"),
    ]

    operations = [
        migrations.AddField(
            model_name="leaf",
            name="att_axis_array",
            field=django.contrib.postgres.fields.ArrayField(
                base_field=models.CharField(
                    choices=[
                        ("ges", "gestielt"),
                        ("sit", "sitzend/ungestielt"),
                        ("ste", "stengelumfassend"),
                        ("hal", "halbstengelumfassend"),
                        ("dur", "durchwachsen"),
                        ("ver", "verwachsen"),
                        ("sch", "scheidig verwachsen"),
                        ("her", "herablaufend"),
                        ("rei", "reitend"),
                        ("hin", "hinfällig"),
                    ],
                    max_length=3,
                    verbose_name="Anheftung an Sprossachse",
                ),
                blank=True,
                default=list,
                size=2,
            ),
        ),
    ]
