# Generated by Django 3.0.8 on 2021-03-23 13:50

from django.db import migrations


def populate_leaf_attachment_with_leaf_att_axis(apps, schema_editor):
    """
    Populate Leaf model attachment fields with att_axis values.
    """
    Leaf = apps.get_model("dive_content", "Leaf")

    for obj in Leaf.objects.all():
        if obj.att_axis:
            obj.attachment = [obj.att_axis]
        else:
            obj.attachment = []
        obj.save()


def populate_leaf_att_axis_with_leaf_attachment(apps, schema_editor):
    """
    Populate Leaf model att_axis fields with attachment first values.
    """
    Leaf = apps.get_model("dive_content", "Leaf")

    for obj in Leaf.objects.all():
        if obj.attachment:
            obj.att_axis = obj.attachment[0]
        else:
            obj.att_axis = ""
        obj.save()


class Migration(migrations.Migration):

    dependencies = [
        ("dive_content", "0050_bulk_alter_leaf"),
    ]

    operations = [
        migrations.RunPython(
            populate_leaf_attachment_with_leaf_att_axis,
            populate_leaf_att_axis_with_leaf_attachment,
        ),
    ]
