# Generated by Django 3.0.8 on 2021-03-07 12:23

from django.db import migrations


def populate_leaf_att_axis_array_with_leaf_att_axis(apps, schema_editor):
    """
    Populate leaf model att_axis_array fields with att_axis values.
    """
    Leaf = apps.get_model("dive_content", "Leaf")

    for obj in Leaf.objects.all():
        if obj.att_axis:
            obj.att_axis_array = [obj.att_axis]
        else:
            obj.att_axis_array = []
        obj.save()


def populate_leaf_att_axis_with_leaf_att_axis_array(apps, schema_editor):
    """
    Populate leaf model att_axis fields with att_axis_array first values.
    """
    Leaf = apps.get_model("dive_content", "Leaf")

    for obj in Leaf.objects.all():
        if obj.att_axis_array:
            obj.att_axis = obj.att_axis_array[0]
        else:
            obj.att_axis = ""
        obj.save()


class Migration(migrations.Migration):

    dependencies = [
        ("dive_content", "0050_add_leaf_att_axis_array"),
    ]

    operations = [
        migrations.RunPython(
            populate_leaf_att_axis_array_with_leaf_att_axis,
            populate_leaf_att_axis_with_leaf_att_axis_array,
        ),
    ]
