# Generated by Django 3.0.8 on 2021-03-07 12:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("dive_content", "0051_populate_leaf_att_axis_array"),
    ]

    operations = [
        migrations.RemoveField(model_name="leaf", name="att_axis",),
    ]
