# Generated by Django 3.0.8 on 2021-03-07 12:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("dive_content", "0052_remove_leaf_att_axis"),
    ]

    operations = [
        migrations.RenameField(
            model_name="leaf", old_name="att_axis_array", new_name="att_axis",
        ),
    ]
