# Generated by Django 3.0.8 on 2021-03-07 15:37

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("dive_content", "0053_rename_leaf_att_axis_array"),
    ]

    operations = [
        migrations.AddField(
            model_name="leaf",
            name="dep_cuts_array",
            field=django.contrib.postgres.fields.ArrayField(
                base_field=models.CharField(
                    choices=[
                        ("gan", "ganz/ungeteilt"),
                        ("gel", "gelappt"),
                        ("gep", "gespalten"),
                        ("get", "geteilt"),
                        ("ges", "geschnitten"),
                        ("gef", "gefingert"),
                        ("zus", "zusammengesetzt"),
                        ("fis", "fiederschnittig"),
                        ("fie", "gefiedert"),
                    ],
                    max_length=3,
                    verbose_name="Tiefe von Einschnitten",
                ),
                blank=True,
                default=list,
                size=2,
            ),
        ),
        migrations.AlterField(
            model_name="leaf",
            name="dep_cuts",
            field=models.CharField(
                blank=True,
                choices=[
                    ("gan", "ganz/ungeteilt"),
                    ("gel", "gelappt"),
                    ("gep", "gespalten"),
                    ("get", "geteilt"),
                    ("ges", "geschnitten"),
                    ("gef", "gefingert"),
                    ("zus", "zusammengesetzt"),
                    ("fis", "fiederschnittig"),
                    ("fie", "gefiedert"),
                ],
                max_length=3,
                verbose_name="Tiefe von Einschnitten",
            ),
        ),
    ]
