# Generated by Django 3.0.8 on 2021-03-07 15:40

from django.db import migrations


def populate_leaf_dep_cuts_array_with_leaf_dep_cuts(apps, schema_editor):
    """
    Populate leaf model dep_cuts_array fields with dep_cuts values.
    """
    Leaf = apps.get_model("dive_content", "Leaf")

    for obj in Leaf.objects.all():
        if obj.dep_cuts:
            obj.dep_cuts_array = [obj.dep_cuts]
        else:
            obj.dep_cuts_array = []
        obj.save()


def populate_leaf_dep_cuts_with_leaf_dep_cuts_array(apps, schema_editor):
    """
    Populate leaf model dep_cuts fields with dep_cuts_array first values.
    """
    Leaf = apps.get_model("dive_content", "Leaf")

    for obj in Leaf.objects.all():
        if obj.dep_cuts_array:
            obj.dep_cuts = obj.dep_cuts_array[0]
        else:
            obj.dep_cuts = ""
        obj.save()


class Migration(migrations.Migration):

    dependencies = [
        ("dive_content", "0054_add_leaf_dep_cuts_array"),
    ]

    operations = [
        migrations.RunPython(
            populate_leaf_dep_cuts_array_with_leaf_dep_cuts,
            populate_leaf_dep_cuts_with_leaf_dep_cuts_array,
        ),
    ]
