# Generated by Django 3.0.8 on 2021-03-23 13:50

from django.db import migrations


def populate_leaf_surface_with_leaf_sur_texture(apps, schema_editor):
    """
    Populate Leaf model surface fields with sur_texture values.
    """
    Leaf = apps.get_model("dive_content", "Leaf")

    for obj in Leaf.objects.all():
        if obj.sur_texture:
            obj.surface = [obj.sur_texture]
        else:
            obj.surface = []
        obj.save()


def populate_leaf_sur_texture_with_leaf_surface(apps, schema_editor):
    """
    Populate Leaf model sur_texture fields with surface first values.
    """
    Leaf = apps.get_model("dive_content", "Leaf")

    for obj in Leaf.objects.all():
        if obj.surface:
            obj.sur_texture = obj.surface[0]
        else:
            obj.sur_texture = ""
        obj.save()


class Migration(migrations.Migration):

    dependencies = [
        ("dive_content", "0055_populate_leaf_edge"),
    ]

    operations = [
        migrations.RunPython(
            populate_leaf_surface_with_leaf_sur_texture,
            populate_leaf_sur_texture_with_leaf_surface,
        ),
    ]
