# Generated by Django 3.0.8 on 2021-03-07 15:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("dive_content", "0055_populate_leaf_dep_cuts_array"),
    ]

    operations = [
        migrations.RemoveField(model_name="leaf", name="dep_cuts",),
    ]
