# Generated by Django 3.0.8 on 2021-03-07 15:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("dive_content", "0056_remove_leaf_dep_cuts"),
    ]

    operations = [
        migrations.RenameField(
            model_name="leaf", old_name="dep_cuts_array", new_name="dep_cuts",
        ),
    ]
