# Generated by Django 3.0.8 on 2021-03-23 13:50

from django.db import migrations


def populate_leaf_stipule_edge_with_leaf_side_leaf(apps, schema_editor):
    """
    Populate leaf model stipule_edge fields with side_leaf values.
    """
    Leaf = apps.get_model("dive_content", "Leaf")

    for obj in Leaf.objects.all():
        if obj.side_leaf:
            obj.stipule_edge = [obj.side_leaf]
        else:
            obj.stipule_edge = []
        obj.save()


def populate_leaf_side_leaf_with_leaf_stipule_edge(apps, schema_editor):
    """
    Populate leaf model side_leaf fields with stipule_edge first values.
    """
    Leaf = apps.get_model("dive_content", "Leaf")

    for obj in Leaf.objects.all():
        if obj.stipule_edge:
            obj.side_leaf = obj.stipule_edge[0]
        else:
            obj.side_leaf = ""
        obj.save()


class Migration(migrations.Migration):

    dependencies = [
        ("dive_content", "0056_populate_leaf_surface"),
    ]

    operations = [
        migrations.RunPython(
            populate_leaf_stipule_edge_with_leaf_side_leaf,
            populate_leaf_side_leaf_with_leaf_stipule_edge,
        ),
    ]
