# Generated by Django 3.0.8 on 2021-03-08 08:30

import django.contrib.postgres.fields
from django.db import migrations, models


def transform_leaf_arr_cuts_forwards(apps, schema_editor):
    ARR_TRANS_FORWARDS = {
        "han": "",
        "hgl": "han",
        "hgt": "han",
        "hgs": "han",
        "fie": "fif",
        "unf": "unt",
        "ung": "unt",
        "dog": "dop",
        "fug": "fus",
        "fuz": "fus",
    }

    Leaf = apps.get_model("dive_content", "Leaf")

    for obj in Leaf.objects.all():
        if obj.arr_cuts in ARR_TRANS_FORWARDS.keys():
            obj.arr_cuts = ARR_TRANS_FORWARDS.get(obj.arr_cuts)
            obj.save()


def transform_leaf_arr_cuts_reverse(apps, schema_editor):
    ARR_TRANS_REVERSE = {
        "han": "",
        "fif": "fie",
        "unt": "",
        "dop": "dog",
        "fus": "",
    }

    Leaf = apps.get_model("dive_content", "Leaf")

    for obj in Leaf.objects.all():
        if obj.arr_cuts in ARR_TRANS_REVERSE.keys():
            obj.arr_cuts = ARR_TRANS_REVERSE.get(obj.arr_cuts)
            obj.save()


class Migration(migrations.Migration):

    dependencies = [
        ("dive_content", "0058_remove_leaf_arr_special"),
    ]

    operations = [
        migrations.AddField(
            model_name="leaf",
            name="blade_div",
            field=django.contrib.postgres.fields.ArrayField(
                base_field=models.CharField(
                    choices=[
                        ("han", "handförmig"),
                        ("gef", "gefingert"),
                        ("fif", "fiederförmig"),
                        ("fil", "fiederlappig"),
                        ("fip", "fiederspaltig"),
                        ("fit", "fiederteilig"),
                        ("fis", "fiederschnittig"),
                        ("paa", "paarig"),
                        ("unp", "unpaarig"),
                        ("unt", "unterbrochen"),
                        ("dop", "doppelt"),
                        ("meh", "mehrfach"),
                        ("dre", "dreizählig"),
                        ("dod", "doppelt dreizählig"),
                        ("lei", "leierförmig"),
                        ("sch", "schrotsägeförmig"),
                        ("kam", "kammförmig"),
                        ("fus", "fußförmig"),
                    ],
                    max_length=3,
                    verbose_name="Gestalt der Spreite (geteiltes Blatt)",
                ),
                blank=True,
                default=list,
                size=2,
            ),
        ),
        migrations.RunPython(
            transform_leaf_arr_cuts_forwards, transform_leaf_arr_cuts_reverse
        ),
        migrations.AlterField(
            model_name="leaf",
            name="arr_cuts",
            field=models.CharField(
                blank=True,
                choices=[
                    ("han", "handförmig"),
                    ("gef", "gefingert"),
                    ("fif", "fiederförmig"),
                    ("fil", "fiederlappig"),
                    ("fip", "fiederspaltig"),
                    ("fit", "fiederteilig"),
                    ("fis", "fiederschnittig"),
                    ("paa", "paarig"),
                    ("unp", "unpaarig"),
                    ("unt", "unterbrochen"),
                    ("dop", "doppelt"),
                    ("meh", "mehrfach"),
                    ("dre", "dreizählig"),
                    ("dod", "doppelt dreizählig"),
                    ("lei", "leierförmig"),
                    ("sch", "schrotsägeförmig"),
                    ("kam", "kammförmig"),
                    ("fus", "fußförmig"),
                ],
                max_length=3,
                verbose_name="Anordnung der Spreite",
            ),
        ),
    ]
