# Generated by Django 3.0.8 on 2021-03-08 09:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("dive_content", "0060_populate_leaf_blade_div"),
    ]

    operations = [
        migrations.RemoveField(model_name="leaf", name="arr_cuts",),
    ]
