# Generated by Django 3.0.8 on 2021-03-08 10:34

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("dive_content", "0061_remove_leaf_arr_cuts"),
    ]

    operations = [
        migrations.AddField(
            model_name="leaf",
            name="blade_undiv",
            field=django.contrib.postgres.fields.ArrayField(
                base_field=models.CharField(
                    choices=[
                        ("kre", "kreisrund"),
                        ("run", "rundlich"),
                        ("ell", "elliptisch"),
                        ("eif", "eiförmig"),
                        ("ver", "verkehrteiförmig"),
                        ("spa", "spatelförmig/spatelig"),
                        ("len", "lanzettlich"),
                        ("eil", "eilanzettlich"),
                        ("lae", "länglich"),
                        ("lin", "linealisch/lineal"),
                        ("nad", "nadelförmig"),
                        ("pfr", "pfriemlich"),
                        ("bor", "borstenförmig/borstlich"),
                        ("fad", "fadenförmig/fädlich"),
                        ("bin", "binsenartig"),
                        ("roe", "röhrig"),
                        ("ser", "schwertförmig"),
                        ("dre", "dreieckig"),
                        ("kei", "keilförmig"),
                        ("rau", "rautenförmig/rhombisch"),
                        ("her", "herzförmig"),
                        ("vhe", "verkehrtherzförmig"),
                        ("nie", "nierenförmig"),
                        ("pfe", "pfeilförmig"),
                        ("spi", "spießförmig"),
                        ("gei", "geigenförmig"),
                        ("sup", "schuppenförmig"),
                        ("sil", "schildförmig"),
                    ],
                    max_length=3,
                    verbose_name="Gestalt der Spreite (ungeteiltes Blatt)",
                ),
                blank=True,
                default=list,
                size=2,
            ),
        ),
    ]
