# Generated by Django 3.0.8 on 2021-03-24 12:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("dive_content", "0062_add_fruit_fruit_form"),
    ]

    operations = [
        migrations.RenameModel(old_name="Sprout", new_name="StemRoot",),
    ]
