# Generated by Django 3.0.8 on 2021-03-08 10:36

from django.db import migrations


def populate_leaf_blade_undiv_with_leaf_form(apps, schema_editor):
    """
    Populate leaf model blade_undiv fields with form values.
    """
    Leaf = apps.get_model("dive_content", "Leaf")

    for obj in Leaf.objects.all():
        if obj.form:
            obj.blade_undiv = [obj.form]
        else:
            obj.blade_undiv = []
        obj.save()


def populate_leaf_form_with_leaf_blade_undiv(apps, schema_editor):
    """
    Populate leaf model form fields with blade_undiv first values.
    """
    Leaf = apps.get_model("dive_content", "Leaf")

    for obj in Leaf.objects.all():
        if obj.blade_undiv:
            obj.form = obj.blade_undiv[0]
        else:
            obj.form = ""
        obj.save()


class Migration(migrations.Migration):

    dependencies = [
        ("dive_content", "0062_add_leaf_blade_undiv"),
    ]

    operations = [
        migrations.RunPython(
            populate_leaf_blade_undiv_with_leaf_form,
            populate_leaf_form_with_leaf_blade_undiv,
        ),
    ]
