# Generated by Django 3.0.8 on 2021-03-24 14:24

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("dive_content", "0064_change_stemroot_meta"),
    ]

    operations = [
        migrations.AddField(
            model_name="stemroot",
            name="appearance",
            field=django.contrib.postgres.fields.ArrayField(
                base_field=models.CharField(
                    choices=[("k", "krautig"), ("h", "holzig")],
                    max_length=1,
                    verbose_name="Erscheinung",
                ),
                blank=True,
                default=list,
                size=2,
            ),
        ),
        migrations.AddField(
            model_name="stemroot",
            name="creep_lay_shoots",
            field=models.CharField(
                blank=True,
                choices=[
                    ("bil", "bildet Kriech- und Legetriebe"),
                    ("kei", "keine Angabe"),
                ],
                max_length=3,
                verbose_name="Kriech- und Legetriebe",
            ),
        ),
        migrations.AddField(
            model_name="stemroot",
            name="cross_section",
            field=django.contrib.postgres.fields.ArrayField(
                base_field=models.CharField(
                    choices=[
                        ("sti", "stielrund"),
                        ("hal", "halbstielrund"),
                        ("zus", "zusammengedrückt"),
                        ("zwe", "zweischneidig"),
                        ("kan", "kantig"),
                        ("stu", "stumpfkantig"),
                        ("ger", "gerieft/gerillt"),
                        ("gef", "gefurcht"),
                        ("kan", "kantig gefurcht/scharfkantig"),
                        ("gri", "gerippt"),
                        ("gfl", "geflügelt"),
                        ("kno", "knotig"),
                    ],
                    max_length=3,
                    verbose_name="Querschnitt",
                ),
                blank=True,
                default=list,
                size=2,
            ),
        ),
        migrations.AddField(
            model_name="stemroot",
            name="organs",
            field=models.CharField(
                blank=True,
                choices=[
                    ("Rhi", "Rhizom"),
                    ("Zwi", "Zwiebel"),
                    ("Aus", "unterirdische Ausläufer"),
                    ("Inn", "Innovations-Wurzelknolle"),
                    ("Wuk", "Wurzelknollen"),
                    ("Wur", "Wurzeln"),
                ],
                max_length=3,
                verbose_name="Organe (unterirdisch)",
            ),
        ),
        migrations.AddField(
            model_name="stemroot",
            name="orientation",
            field=django.contrib.postgres.fields.ArrayField(
                base_field=models.CharField(
                    choices=[
                        ("auf", "aufrecht"),
                        ("aua", "aufrecht-abstehend"),
                        ("abs", "abstehend"),
                        ("spa", "sparrig"),
                        ("zur", "zurückgeschlagen"),
                        ("lie", "liegend"),
                        ("kri", "kriechend"),
                        ("aus", "aufsteigend/aufstrebend"),
                        ("gek", "gekniet"),
                        ("ueb", "übergebogen"),
                        ("nic", "nickend"),
                        ("hae", "hängend"),
                        ("flu", "flutend"),
                        ("hor", "horstig"),
                        ("loc", "lockerrasig"),
                        ("ran", "rankenpflanzen"),
                        ("win", "windepflanzen"),
                        ("spr", "spreizklimmig"),
                        ("wur", "wurzelkletternd"),
                    ],
                    max_length=3,
                    verbose_name="Wuchsorientierung",
                ),
                blank=True,
                default=list,
                size=2,
            ),
        ),
        migrations.AddField(
            model_name="stemroot",
            name="organ_features",
            field=models.CharField(
                blank=True,
                help_text="Besondere Ausprägungen der unterirdischen Organe.",
                max_length=100,
                verbose_name="Besonderheiten",
            ),
        ),
        migrations.AddField(
            model_name="stemroot",
            name="runners",
            field=models.CharField(
                blank=True,
                choices=[
                    ("bil", "bildet oberirdische Ausläufer"),
                    ("kei", "keine Angabe"),
                ],
                max_length=3,
                verbose_name="Ausläufer (oberirdisch)",
            ),
        ),
        migrations.AddField(
            model_name="stemroot",
            name="surface",
            field=django.contrib.postgres.fields.ArrayField(
                base_field=models.CharField(
                    choices=[
                        ("gla", "glatt"),
                        ("run", "runzelig"),
                        ("rau", "rauh"),
                        ("vra", "vorwärts rauh"),
                        ("ber", "bereift"),
                        ("bes", "bestäubt/bemehlt"),
                        ("pap", "papillös"),
                        ("pun", "punktiert"),
                        ("swi", "schwielig"),
                        ("kah", "kahl"),
                        ("ver", "verkahlend"),
                        ("fla", "flaumhaarig/weichhaarig"),
                        ("sei", "seidenhaarig"),
                        ("spi", "spinnwebig"),
                        ("flo", "flockig"),
                        ("sam", "samthaarig"),
                        ("fil", "filzig"),
                        ("wol", "wollig"),
                        ("zot", "zottig"),
                        ("rah", "rauhaarig"),
                        ("ste", "steifhaarig"),
                        ("gew", "gewimpert"),
                        ("dru", "drüsenhaarig"),
                        ("ste", "sternhaarig"),
                        ("sdh", "schildhaarig"),
                        ("sup", "schuppenhaarig/schuppig"),
                        ("sue", "schülferig"),
                        ("bae", "bärtig"),
                        ("ach", "achselbärtig"),
                        ("nac", "nackt"),
                    ],
                    max_length=3,
                    verbose_name="Sprossoberfläche",
                ),
                blank=True,
                default=list,
                size=2,
            ),
        ),
    ]
