# Generated by Django 3.0.8 on 2021-03-10 07:32

from django.db import migrations


def populate_leaf_margin_with_leaf_leaflets(apps, schema_editor):
    """
    Populate leaf model margin fields with leaflets values.
    """
    Leaf = apps.get_model("dive_content", "Leaf")

    for obj in Leaf.objects.all():
        if obj.leaflets:
            obj.margin = [obj.leaflets]
        else:
            obj.margin = []
        obj.save()


def populate_leaf_leaflets_with_leaf_margin(apps, schema_editor):
    """
    Populate leaf model leaflets fields with margin first values.
    """
    Leaf = apps.get_model("dive_content", "Leaf")

    for obj in Leaf.objects.all():
        if obj.margin:
            obj.leaflets = obj.margin[0]
        else:
            obj.leaflets = ""
        obj.save()


class Migration(migrations.Migration):

    dependencies = [
        ("dive_content", "0065_add_leaf_margin"),
    ]

    operations = [
        migrations.RunPython(
            populate_leaf_margin_with_leaf_leaflets,
            populate_leaf_leaflets_with_leaf_margin,
        ),
    ]
