# Generated by Django 3.0.8 on 2021-03-10 07:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("dive_content", "0066_populate_leaf_margin"),
    ]

    operations = [
        migrations.RemoveField(model_name="leaf", name="leaflets",),
    ]
