# Generated by Django 3.0.8 on 2021-03-24 14:56

from django.db import migrations


def populate_stemroot_appearance_with_stemroot_appear(apps, schema_editor):
    """
    Populate StemRoot model appearance fields with appear values.
    """
    StemRoot = apps.get_model("dive_content", "StemRoot")

    for obj in StemRoot.objects.all():
        if obj.appear:
            obj.appearance = [obj.appear]
        else:
            obj.appearance = []
        obj.save()


def populate_stemroot_appear_with_stemroot_appearance(apps, schema_editor):
    """
    Populate StemRoot model appear fields with appearance first values.
    """
    StemRoot = apps.get_model("dive_content", "StemRoot")

    for obj in StemRoot.objects.all():
        if obj.appearance:
            obj.appear = obj.appearance[0]
        else:
            obj.appear = ""
        obj.save()


class Migration(migrations.Migration):

    dependencies = [
        ("dive_content", "0066_populate_stemroot_orientation"),
    ]

    operations = [
        migrations.RunPython(
            populate_stemroot_appearance_with_stemroot_appear,
            populate_stemroot_appear_with_stemroot_appearance,
        ),
    ]
