# Generated by Django 3.0.8 on 2021-03-24 15:06

from django.db import migrations


def populate_stemroot_cross_section_with_stemroot_diam(apps, schema_editor):
    """
    Populate StemRoot model cross_section fields with diam values.
    """
    StemRoot = apps.get_model("dive_content", "StemRoot")

    for obj in StemRoot.objects.all():
        if obj.diam:
            obj.cross_section = [obj.diam]
        else:
            obj.cross_section = []
        obj.save()


def populate_stemroot_diam_with_stemroot_cross_section(apps, schema_editor):
    """
    Populate StemRoot model diam fields with cross_section first values.
    """
    StemRoot = apps.get_model("dive_content", "StemRoot")

    for obj in StemRoot.objects.all():
        if obj.cross_section:
            obj.diam = obj.cross_section[0]
        else:
            obj.diam = ""
        obj.save()


class Migration(migrations.Migration):

    dependencies = [
        ("dive_content", "0067_populate_stemroot_appearance"),
    ]

    operations = [
        migrations.RunPython(
            populate_stemroot_cross_section_with_stemroot_diam,
            populate_stemroot_diam_with_stemroot_cross_section,
        ),
    ]
