# Generated by Django 3.0.8 on 2021-03-24 15:15

from django.db import migrations


def populate_stemroot_surface_with_stemroot_sur_texture(apps, schema_editor):
    """
    Populate StemRoot model surface fields with sur_texture values.
    """
    StemRoot = apps.get_model("dive_content", "StemRoot")

    for obj in StemRoot.objects.all():
        if obj.sur_texture:
            obj.surface = [obj.sur_texture]
        else:
            obj.surface = []
        obj.save()


def populate_stemroot_sur_texture_with_stemroot_surface(apps, schema_editor):
    """
    Populate StemRoot model sur_texture fields with surface first values.
    """
    StemRoot = apps.get_model("dive_content", "StemRoot")

    for obj in StemRoot.objects.all():
        if obj.surface:
            obj.sur_texture = obj.surface[0]
        else:
            obj.sur_texture = ""
        obj.save()


class Migration(migrations.Migration):

    dependencies = [
        ("dive_content", "0068_populate_stemroot_cross_section"),
    ]

    operations = [
        migrations.RunPython(
            populate_stemroot_surface_with_stemroot_sur_texture,
            populate_stemroot_sur_texture_with_stemroot_surface,
        ),
    ]
