# Generated by Django 3.0.8 on 2021-03-24 15:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("dive_content", "0069_populate_stemroot_surface"),
    ]

    operations = [
        migrations.RemoveField(model_name="stemroot", name="appear",),
        migrations.RemoveField(model_name="stemroot", name="blade",),
        migrations.RemoveField(model_name="stemroot", name="cluster",),
        migrations.RemoveField(model_name="stemroot", name="diam",),
        migrations.RemoveField(model_name="stemroot", name="pos",),
        migrations.RemoveField(model_name="stemroot", name="sur_texture",),
    ]
