# Generated by Django 3.0.8 on 2021-03-24 16:16

from django.db import migrations, models


def update_stemroot_succulence_forwards(apps, schema_editor):
    SUCCULENCE_UPDATE_FORWARDS = {None: "", "yes": "dic", "no": "ndi"}

    StemRoot = apps.get_model("dive_content", "StemRoot")

    for obj in StemRoot.objects.all():
        obj.succulence = SUCCULENCE_UPDATE_FORWARDS.get(obj.succulence, "")
        obj.save()


def update_stemroot_succulence_reverse(apps, schema_editor):
    SUCCULENCE_UPDATE_REVERSE = {"": None, "dic": "yes", "ndi": "no"}

    StemRoot = apps.get_model("dive_content", "StemRoot")

    for obj in StemRoot.objects.all():
        obj.succulence = SUCCULENCE_UPDATE_REVERSE.get(obj.succulence, None)
        obj.save()


def prune_stemroot_milky_sap(apps, schema_editor):
    StemRoot = apps.get_model("dive_content", "StemRoot")

    for obj in StemRoot.objects.exclude(milky_sap=""):
        obj.milky_sap = obj.milky_sap[:3]
        obj.save()


class Migration(migrations.Migration):

    dependencies = [
        ("dive_content", "0071_bulk_rename_stemroot"),
    ]

    operations = [
        migrations.RunPython(
            update_stemroot_succulence_forwards, update_stemroot_succulence_reverse
        ),
        migrations.AlterField(
            model_name="stemroot",
            name="succulence",
            field=models.CharField(
                blank=True,
                choices=[("dic", "dickfleischig"), ("ndi", "nicht dickfleischig")],
                default="",
                max_length=3,
                verbose_name="Dickfleischigkeit",
            ),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="stemroot",
            name="bracts",
            field=models.CharField(
                blank=True,
                choices=[("nur", "nur am Grund"), ("auc", "auch über dem Grund")],
                max_length=3,
                verbose_name="Beblätterung",
            ),
        ),
        migrations.SeparateDatabaseAndState(
            database_operations=[
                migrations.RunPython(
                    migrations.RunPython.noop, prune_stemroot_milky_sap
                ),
            ],
            state_operations=[
                migrations.AlterField(
                    model_name="stemroot",
                    name="milky_sap",
                    field=models.CharField(
                        blank=True,
                        default="",
                        help_text="Bsp. kein Milchsaft, gelber Milchsaft, etc.",
                        max_length=100,
                        verbose_name="Milchsaft",
                    ),
                    preserve_default=False,
                ),
            ],
        ),
        migrations.AlterField(
            model_name="stemroot",
            name="primary_root",
            field=models.CharField(
                blank=True,
                choices=[
                    ("erh", "erhalten"),
                    ("ers", "durch sprossbürtige Wurzeln ersetzt"),
                ],
                max_length=3,
                verbose_name="Primärwurzel",
            ),
        ),
    ]
