# Generated by Django 3.0.8 on 2021-03-10 09:17

from django.db import migrations


def populate_leaf_stipule_margin_with_leaf_side_leaf(apps, schema_editor):
    """
    Populate leaf model stipule_margin fields with side_leaf values.
    """
    Leaf = apps.get_model("dive_content", "Leaf")

    for obj in Leaf.objects.all():
        if obj.side_leaf:
            obj.stipule_margin = [obj.side_leaf]
        else:
            obj.stipule_margin = []
        obj.save()


def populate_leaf_side_leaf_with_leaf_stipule_margin(apps, schema_editor):
    """
    Populate leaf model side_leaf fields with stipule_margin first values.
    """
    Leaf = apps.get_model("dive_content", "Leaf")

    for obj in Leaf.objects.all():
        if obj.stipule_margin:
            obj.side_leaf = obj.stipule_margin[0]
        else:
            obj.side_leaf = ""
        obj.save()


class Migration(migrations.Migration):

    dependencies = [
        ("dive_content", "0071_add_leaf_stipule_margin"),
    ]

    operations = [
        migrations.RunPython(
            populate_leaf_stipule_margin_with_leaf_side_leaf,
            populate_leaf_side_leaf_with_leaf_stipule_margin,
        ),
    ]
