# Generated by Django 3.0.8 on 2021-03-24 16:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("dive_content", "0071_bulk_rename_stemroot"),
    ]

    operations = [
        migrations.AlterField(
            model_name="stemroot",
            name="succulence",
            field=models.CharField(
                blank=True,
                choices=[("dic", "dickfleischig"), ("ndi", "nicht dickfleischig")],
                default="",
                max_length=3,
                verbose_name="Dickfleischigkeit",
            ),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="stemroot",
            name="bracts",
            field=models.CharField(
                blank=True,
                choices=[("nur", "nur am Grund"), ("auc", "auch über dem Grund")],
                max_length=3,
                verbose_name="Beblätterung",
            ),
        ),
        migrations.AlterField(
            model_name="stemroot",
            name="milky_sap",
            field=models.CharField(
                blank=True,
                default="",
                help_text="Bsp. kein Milchsaft, gelber Milchsaft, etc.",
                max_length=100,
                verbose_name="Milchsaft",
            ),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="stemroot",
            name="primary_root",
            field=models.CharField(
                blank=True,
                choices=[
                    ("erh", "erhalten"),
                    ("ers", "durch sprossbürtige Wurzeln ersetzt"),
                ],
                max_length=3,
                verbose_name="Primärwurzel",
            ),
        ),
    ]
