# Generated by Django 3.0.8 on 2021-03-10 09:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("dive_content", "0072_populate_leaf_stipule_margin"),
    ]

    operations = [
        migrations.RemoveField(model_name="leaf", name="side_leaf",),
    ]
