# Generated by Django 3.0.8 on 2021-04-27 20:57

from django.db import migrations


def update_stemroot_succulence_forwards(apps, schema_editor):
    SUCCULENCE_UPDATE_FORWARDS = {None: "", "yes": "dic", "no": "ndi"}

    StemRoot = apps.get_model("dive_content", "StemRoot")

    for obj in StemRoot.objects.all():
        obj.succulence = SUCCULENCE_UPDATE_FORWARDS.get(obj.succulence, "")
        obj.save()


def update_stemroot_succulence_reverse(apps, schema_editor):
    SUCCULENCE_UPDATE_REVERSE = {"dic": "yes", "ndi": "no"}

    StemRoot = apps.get_model("dive_content", "StemRoot")

    for obj in StemRoot.objects.exclude(succulence=""):
        obj.succulence = SUCCULENCE_UPDATE_REVERSE.get(obj.succulence, "")
        obj.save()


def prune_stemroot_milky_sap(apps, schema_editor):
    StemRoot = apps.get_model("dive_content", "StemRoot")

    for obj in StemRoot.objects.exclude(milky_sap=""):
        obj.milky_sap = obj.milky_sap[:3]
        obj.save()


class Migration(migrations.Migration):

    dependencies = [
        ("dive_content", "0072_bulk_alter_stemroot"),
    ]

    operations = [
        migrations.RunPython(
            update_stemroot_succulence_forwards, update_stemroot_succulence_reverse
        ),
        migrations.RunPython(migrations.RunPython.noop, prune_stemroot_milky_sap),
    ]
