# Generated by Django 3.0.8 on 2021-04-01 09:45
import django.contrib.postgres.fields
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("dive_content", "0073_bulk_update_stemroot"),
    ]

    operations = [
        migrations.CreateModel(
            name="Indicators",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "not_specified",
                    models.BooleanField(
                        default=False,
                        help_text="Die Ausgabe aller Zeigerwerte wird unterdrückt.",
                        verbose_name="Keine Angabe",
                    ),
                ),
                (
                    "light",
                    models.CharField(
                        blank=True, max_length=10, verbose_name="Lichtzahl"
                    ),
                ),
                (
                    "temperature",
                    models.CharField(
                        blank=True, max_length=10, verbose_name="Temperaturzahl"
                    ),
                ),
                (
                    "humidity",
                    models.CharField(
                        blank=True, max_length=10, verbose_name="Feuchtezahl"
                    ),
                ),
                (
                    "reaction",
                    models.CharField(
                        blank=True, max_length=10, verbose_name="Reaktionszahl"
                    ),
                ),
                (
                    "nitrogen",
                    models.CharField(
                        blank=True, max_length=10, verbose_name="Stickstoffzahl"
                    ),
                ),
                (
                    "key",
                    django.contrib.postgres.fields.ArrayField(
                        base_field=models.CharField(max_length=3),
                        default=list,
                        editable=False,
                        size=None,
                    ),
                ),
                (
                    "plant",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="indicators",
                        to="dive_content.Plant",
                        verbose_name="Pflanze",
                    ),
                ),
            ],
            options={
                "verbose_name": "Zeigerwerte",
                "verbose_name_plural": "Zeigerwerte",
            },
        ),
    ]
