# Generated by Django 3.0.8 on 2021-04-02 13:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("dive_content", "0073_create_indicators"),
    ]

    operations = [
        migrations.DeleteModel(name="ZeigerNumber",),
    ]
