# Generated by Django 3.0.8 on 2021-03-11 08:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("dive_content", "0074_alter_leaf_margin_and_stipule_margin"),
    ]

    operations = [
        migrations.RenameField(
            model_name="leaf", old_name="thick_flesh", new_name="succulence",
        ),
    ]
