# Generated by Django 3.0.8 on 2021-04-19 23:03

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("dive_content", "0076_rename_blossom_season"),
    ]

    operations = [
        migrations.AddField(
            model_name="blossom",
            name="bract_blade",
            field=django.contrib.postgres.fields.ArrayField(
                base_field=models.CharField(
                    choices=[
                        ("han", "handförmig"),
                        ("gef", "gefingert"),
                        ("fif", "fiederförmig"),
                        ("fil", "fiederlappig"),
                        ("fip", "fiederspaltig"),
                        ("fit", "fiederteilig"),
                        ("fis", "fiederschnittig"),
                        ("paa", "paarig"),
                        ("unp", "unpaarig"),
                        ("unt", "unterbrochen"),
                        ("dop", "doppelt"),
                        ("meh", "mehrfach"),
                        ("dre", "dreizählig"),
                        ("dod", "doppelt dreizählig"),
                        ("lei", "leierförmig"),
                        ("sch", "schrotsägeförmig"),
                        ("kam", "kammförmig"),
                        ("fus", "fußförmig"),
                        ("kre", "kreisrund"),
                        ("run", "rundlich"),
                        ("ell", "elliptisch"),
                        ("eif", "eiförmig"),
                        ("ver", "verkehrteiförmig"),
                        ("spa", "spatelförmig/spatelig"),
                        ("len", "lanzettlich"),
                        ("eil", "eilanzettlich"),
                        ("lae", "länglich"),
                        ("lin", "linealisch/lineal"),
                        ("nad", "nadelförmig"),
                        ("pfr", "pfriemlich"),
                        ("bor", "borstenförmig/borstlich"),
                        ("fad", "fadenförmig/fädlich"),
                        ("bin", "binsenartig"),
                        ("roe", "röhrig"),
                        ("ser", "schwertförmig"),
                        ("dre", "dreieckig"),
                        ("kei", "keilförmig"),
                        ("rau", "rautenförmig/rhombisch"),
                        ("her", "herzförmig"),
                        ("vhe", "verkehrtherzförmig"),
                        ("nie", "nierenförmig"),
                        ("pfe", "pfeilförmig"),
                        ("spi", "spießförmig"),
                        ("gei", "geigenförmig"),
                        ("sup", "schuppenförmig"),
                        ("sil", "schildförmig"),
                        ("nvo", "nicht vorhanden"),
                    ],
                    max_length=3,
                    verbose_name="Tragblattspreite",
                ),
                blank=True,
                default=list,
                size=2,
            ),
        ),
        migrations.AddField(
            model_name="blossom",
            name="diameter",
            field=models.CharField(
                blank=True, max_length=10, verbose_name="Durchmesser"
            ),
        ),
        migrations.AddField(
            model_name="blossom",
            name="inflorescence_num",
            field=models.CharField(
                blank=True, max_length=10, verbose_name="Blütenstandsanzahl"
            ),
        ),
        migrations.AddField(
            model_name="blossom",
            name="petal_num",
            field=models.CharField(
                blank=True, max_length=10, verbose_name="Kronblattanzahl"
            ),
        ),
        migrations.AddField(
            model_name="blossom",
            name="season",
            field=django.contrib.postgres.fields.ArrayField(
                base_field=models.IntegerField(
                    blank=True, null=True, verbose_name="Blütezeit"
                ),
                blank=True,
                default=list,
                size=4,
            ),
        ),
        migrations.AddField(
            model_name="blossom",
            name="sepal_color_form",
            field=models.CharField(
                blank=True, max_length=100, verbose_name="Farbe/Gestalt (Kelchblatt)"
            ),
        ),
        migrations.AddField(
            model_name="blossom",
            name="sepal_connation",
            field=models.CharField(
                blank=True,
                choices=[
                    ("v", "verwachsen"),
                    ("u", "unverwachsen"),
                    ("a", "am Grund verwachsen"),
                ],
                max_length=1,
                verbose_name="Verwachsung (Kelchblatt)",
            ),
        ),
        migrations.AddField(
            model_name="blossom",
            name="sepal_num",
            field=models.CharField(
                blank=True, max_length=10, verbose_name="Kelchblattanzahl"
            ),
        ),
        migrations.AddField(
            model_name="blossom",
            name="stamen_connation_type_add",
            field=models.CharField(
                blank=True, max_length=100, verbose_name="Verwachsungstypzusatz"
            ),
        ),
    ]
