# Generated by Django 3.0.8 on 2021-03-11 10:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("dive_content", "0076_alter_leaf_succulence"),
    ]

    operations = [
        migrations.AddField(
            model_name="leaf",
            name="rosette",
            field=models.CharField(
                blank=True,
                choices=[
                    ("vor", "Grundblattrossette vorhanden"),
                    ("kei", "keine Grundblattrosette"),
                ],
                max_length=3,
                verbose_name="Grundblattrosette",
            ),
        ),
    ]
