# Generated by Django 3.0.8 on 2021-04-19 23:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("dive_content", "0077_bulk_add_blossom"),
    ]

    operations = [
        migrations.RenameField(
            model_name="blossom", old_name="bl_cnt", new_name="blossom_num",
        ),
        migrations.RenameField(
            model_name="blossom",
            old_name="fruit_build",
            new_name="carpel_connation_type",
        ),
        migrations.RenameField(
            model_name="blossom", old_name="fruit_cnt", new_name="carpel_num",
        ),
        migrations.RenameField(
            model_name="blossom", old_name="sec_out", new_name="epicalyx",
        ),
        migrations.RenameField(
            model_name="blossom", old_name="type", new_name="inflorescence_type",
        ),
        migrations.RenameField(
            model_name="blossom", old_name="cnt", new_name="merosity",
        ),
        migrations.RenameField(
            model_name="blossom", old_name="spec_hon", new_name="nectary",
        ),
        migrations.RenameField(
            model_name="blossom", old_name="fruit_stand", new_name="ovary_pos",
        ),
        migrations.RenameField(
            model_name="blossom", old_name="hull", new_name="perianth",
        ),
        migrations.RenameField(
            model_name="blossom", old_name="spec_sporn", new_name="perianth_form",
        ),
        migrations.RenameField(
            model_name="blossom", old_name="crown_color", new_name="petal_color_form",
        ),
        migrations.RenameField(
            model_name="blossom", old_name="crown_ver", new_name="petal_connation",
        ),
        migrations.RenameField(
            model_name="blossom",
            old_name="crown_lower",
            new_name="petal_connation_type",
        ),
        migrations.RenameField(
            model_name="blossom", old_name="crown_plate", new_name="petal_len",
        ),
        migrations.RenameField(
            model_name="blossom", old_name="griffel_stand", new_name="pistil_pos",
        ),
        migrations.RenameField(
            model_name="blossom", old_name="ch_type", new_name="sepal_connation_type",
        ),
        migrations.RenameField(
            model_name="blossom", old_name="dust_color", new_name="stamen_color_form",
        ),
        migrations.RenameField(
            model_name="blossom",
            old_name="dust_pipe",
            new_name="stamen_connation_type",
        ),
        migrations.RenameField(
            model_name="blossom", old_name="dust_len", new_name="stamen_len",
        ),
        migrations.RenameField(
            model_name="blossom", old_name="dust_cnt", new_name="stamen_num",
        ),
        migrations.RenameField(
            model_name="blossom", old_name="fruit_scar", new_name="stigma_num",
        ),
        migrations.RenameField(
            model_name="blossom", old_name="spec_pol", new_name="stylopodium",
        ),
        migrations.RenameField(
            model_name="blossom", old_name="sym", new_name="symmetry",
        ),
    ]
