# Generated by Django 3.0.8 on 2021-03-11 11:27

from django.db import migrations


def populate_leaf_rosette_with_sprout_rose(apps, schema_editor):
    """
    Populate Leaf model rosette fields with Sprout model rose values.
    """
    Sprout = apps.get_model("dive_content", "sprout")
    Leaf = apps.get_model("dive_content", "leaf")

    for obj in Sprout.objects.exclude(rose=None).prefetch_related("plant__leaf"):
        if obj.rose == "fal":
            rosette = "kei"
        else:
            rosette = "vor"

        try:
            obj.plant.leaf.rosette = rosette
            obj.plant.leaf.save()
        except Leaf.DoesNotExist:
            Leaf.objects.create(plant=obj.plant, rosette=rosette)


def populate_sprout_rose_with_leaf_rosette(apps, schema_editor):
    """
    Populate Sprout model rose fields with Leaf model rosette values.
    """
    Leaf = apps.get_model("dive_content", "leaf")
    Sprout = apps.get_model("dive_content", "sprout")

    for obj in Leaf.objects.exclude(rosette="").prefetch_related("plant__sprout"):
        if obj.rosette == "vor":
            rose = "tru"
        else:
            rose = "fal"

        try:
            obj.plant.sprout.rose = rose
            obj.plant.sprout.save()
        except Sprout.DoesNotExist:
            Sprout.objects.create(plant=obj.plant, rose=rose)


class Migration(migrations.Migration):

    dependencies = [
        ("dive_content", "0077_add_leaf_rosette"),
    ]

    operations = [
        migrations.RunPython(
            populate_leaf_rosette_with_sprout_rose,
            populate_sprout_rose_with_leaf_rosette,
        ),
    ]
