# Generated by Django 3.0.8 on 2021-04-19 23:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("dive_content", "0078_bulk_rename_blossom"),
    ]

    operations = [
        migrations.AlterField(
            model_name="blossom",
            name="blossom_num",
            field=models.CharField(
                blank=True, max_length=10, verbose_name="Blütenanzahl (pro Stand)"
            ),
        ),
        migrations.AlterField(
            model_name="blossom",
            name="carpel_connation_type",
            field=models.CharField(
                blank=True,
                choices=[
                    ("mo", "monokarp"),
                    ("ap", "apokarp/chorikarp"),
                    ("cs", "coeno-synkarp"),
                    ("cp", "coeno-parakarp"),
                ],
                max_length=2,
                verbose_name="Verwachsungstyp (Fruchtblatt)",
            ),
        ),
        migrations.AlterField(
            model_name="blossom",
            name="carpel_num",
            field=models.CharField(
                blank=True, max_length=10, verbose_name="Fruchtblattanzahl"
            ),
        ),
        migrations.AlterField(
            model_name="blossom",
            name="inflorescence_type",
            field=models.CharField(
                blank=True,
                choices=[
                    ("kol", "Kolben"),
                    ("kae", "Kätzchen"),
                    ("zap", "Zapfen"),
                    ("koc", "Köpfchen"),
                    ("krc", "Körbchen"),
                    ("bue", "Büschel"),
                    ("kna", "Knäuel"),
                    ("ein", "Einzelblüte"),
                    ("tra", "Traube"),
                    ("ris", "Rispe"),
                    ("sct", "Schirmtraube"),
                    ("scr", "Schirmrispe"),
                    ("spi", "Spirre/Trichterrispe"),
                    ("aer", "Ähre"),
                    ("dol", "Dolde"),
                    ("dod", "Doppeldolde"),
                    ("zym", "Zyme"),
                    ("wic", "Wickel"),
                    ("dow", "Doppelwickel"),
                    ("thy", "Thyrse"),
                    ("scd", "Scheindolde/Trugdolde"),
                    ("ebe", "Ebenstrauß/Corymbus"),
                    ("kop", "Kopf"),
                    ("kor", "Korb"),
                    ("ple", "Pleiochasium"),
                    ("dic", "Dichasium"),
                    ("mon", "Monochasium"),
                    ("scq", "Scheinquirl"),
                    ("scb", "Scheinblüte/Pseudanthium"),
                ],
                max_length=3,
                verbose_name="Blütenstandstyp",
            ),
        ),
        migrations.AlterField(
            model_name="blossom",
            name="merosity",
            field=models.IntegerField(
                blank=True,
                choices=[
                    (None, "-"),
                    (2, "2"),
                    (3, "3"),
                    (4, "4"),
                    (5, "5"),
                    (6, "6"),
                    (7, "7"),
                    (8, "8"),
                    (9, "viel"),
                ],
                null=True,
                verbose_name="Zähligkeit",
            ),
        ),
        migrations.AlterField(
            model_name="blossom",
            name="nectary",
            field=models.CharField(
                blank=True, max_length=100, verbose_name="Nektarium/Honigdrüse"
            ),
        ),
        migrations.AlterField(
            model_name="blossom",
            name="ovary_pos",
            field=models.CharField(
                blank=True,
                choices=[
                    ("ob", "oberständig"),
                    ("ho", "halboberständig"),
                    ("mi", "mittelständig"),
                    ("hu", "halbunterständig"),
                    ("un", "unterständig"),
                ],
                max_length=2,
                verbose_name="Fruchtknotenstellung",
            ),
        ),
        migrations.AlterField(
            model_name="blossom",
            name="perianth",
            field=models.CharField(
                blank=True,
                choices=[
                    ("dop", "doppelte Blütenhülle (Kalyx + Corolla)"),
                    ("ein", "einfache Blütenhülle (Perigon)"),
                    ("feh", "fehlende Blütenhülle"),
                    ("lip", "Lippenblüte"),
                    ("sch", "Schmetterlingsblüte"),
                    ("zun", "Zungenblüte"),
                    ("roe", "Röhrenblüte"),
                    ("str", "strahlende Randblüten"),
                ],
                max_length=3,
                verbose_name="Blütenhülle",
            ),
        ),
        migrations.AlterField(
            model_name="blossom",
            name="perianth_form",
            field=models.CharField(
                blank=True,
                choices=[
                    ("ro", "röhrig"),
                    ("ke", "keulig"),
                    ("gl", "glockig"),
                    ("tr", "trichterförmig"),
                    ("be", "becherförmig"),
                    ("na", "napfförmig"),
                    ("ku", "kugelig"),
                    ("au", "aufgeblasen"),
                    ("kr", "krugförmig"),
                    ("ra", "radförmig"),
                    ("st", "stielförmig"),
                    ("zu", "zungenförmig"),
                    ("ba", "bauchig"),
                    ("as", "ausgesackt"),
                    ("gr", "gespornt"),
                ],
                max_length=2,
                verbose_name="Blütenhüllenform (verwachsenblättrig)",
            ),
        ),
        migrations.AlterField(
            model_name="blossom",
            name="petal_color_form",
            field=models.CharField(
                blank=True, max_length=100, verbose_name="Farbe/Gestalt (Kronblatt)"
            ),
        ),
        migrations.AlterField(
            model_name="blossom",
            name="petal_connation",
            field=models.CharField(
                blank=True,
                choices=[
                    ("v", "verwachsen"),
                    ("u", "unverwachsen"),
                    ("a", "am Grund verwachsen"),
                ],
                max_length=1,
                verbose_name="Verwachsung (Kronblatt)",
            ),
        ),
        migrations.AlterField(
            model_name="blossom",
            name="petal_connation_type",
            field=models.CharField(
                blank=True, max_length=3, verbose_name="Verwachsungstyp (Kronblatt)"
            ),
        ),
        migrations.AlterField(
            model_name="blossom",
            name="petal_len",
            field=models.CharField(
                blank=True, max_length=10, verbose_name="Kronblattlänge (Platte)"
            ),
        ),
        migrations.AlterField(
            model_name="blossom",
            name="pistil_pos",
            field=models.CharField(
                blank=True,
                choices=[
                    ("end", "endständig"),
                    ("sei", "seitenständig"),
                    ("gru", "grundständig"),
                    ("gyn", "gynobasisch"),
                    ("sen", "subendständig"),
                    ("sse", "subseitenständig"),
                    ("sgr", "subgrundständig"),
                    ("sgy", "subgynobasisch"),
                ],
                max_length=3,
                verbose_name="Griffelstellung",
            ),
        ),
        migrations.AlterField(
            model_name="blossom",
            name="sepal_connation_type",
            field=models.CharField(
                blank=True, max_length=3, verbose_name="Verwachsungstyp (Kelchblatt)"
            ),
        ),
        migrations.AlterField(
            model_name="blossom",
            name="stamen_color_form",
            field=models.CharField(
                blank=True, max_length=100, verbose_name="Farbe/Gestalt (Staubblatt)"
            ),
        ),
        migrations.AlterField(
            model_name="blossom",
            name="stamen_connation_type",
            field=models.CharField(
                blank=True,
                choices=[
                    ("s", "Staubfadenröhre"),
                    ("v", "verwachsen mit Kronblättern"),
                ],
                max_length=1,
                verbose_name="Verwachsungstyp (Staubblatt)",
            ),
        ),
        migrations.AlterField(
            model_name="blossom",
            name="stamen_len",
            field=models.CharField(
                blank=True, max_length=10, verbose_name="Staubblattlänge"
            ),
        ),
        migrations.AlterField(
            model_name="blossom",
            name="stamen_num",
            field=models.CharField(
                blank=True, max_length=10, verbose_name="Staubblattanzahl"
            ),
        ),
        migrations.AlterField(
            model_name="blossom",
            name="stigma_num",
            field=models.CharField(
                blank=True, max_length=10, verbose_name="Narbenanzahl (pro Griffel)"
            ),
        ),
        migrations.AlterField(
            model_name="blossom",
            name="symmetry",
            field=models.CharField(
                blank=True,
                choices=[
                    ("r", "radiärsymmetrisch"),
                    ("d", "disymmetrisch"),
                    ("z", "zygomorph"),
                    ("a", "asymmetrisch"),
                ],
                max_length=1,
                verbose_name="Symmetrie",
            ),
        ),
    ]
