# Generated by Django 3.0.8 on 2021-04-20 01:29

from django.db import migrations


def prune_blossom_merosity(apps, schema_editor):
    Blossom = apps.get_model("dive_content", "Blossom")

    for obj in Blossom.objects.exclude(merosity=None):
        if obj.merosity in (2, 6, 7, 8, 9):
            obj.merosity = None
            obj.save()


def update_blossom_ovary_pos_forwards(apps, schema_editor):
    OVARY_POS_UPDATE_FORWARDS = {
        "hy": "ob",
        "eh": "ho",
        "pe": "mi",
        "he": "hu",
        "ep": "un",
    }

    Blossom = apps.get_model("dive_content", "Blossom")

    for obj in Blossom.objects.exclude(ovary_pos=""):
        obj.ovary_pos = OVARY_POS_UPDATE_FORWARDS.get(obj.ovary_pos, "")
        obj.save()


def update_blossom_ovary_pos_reverse(apps, schema_editor):
    OVARY_POS_UPDATE_REVERSE = {
        "ob": "hy",
        "ho": "eh",
        "mi": "pe",
        "hu": "he",
        "un": "ep",
    }

    Blossom = apps.get_model("dive_content", "Blossom")

    for obj in Blossom.objects.exclude(ovary_pos=""):
        obj.ovary_pos = OVARY_POS_UPDATE_REVERSE.get(obj.ovary_pos, "")
        obj.save()


def update_blossom_pistil_pos_forwards(apps, schema_editor):
    PISTIL_POS_UPDATE_FORWARDS = {"en": "end", "se": "sei", "gr": "gru", "gy": "gyn"}

    Blossom = apps.get_model("dive_content", "Blossom")

    for obj in Blossom.objects.exclude(pistil_pos=""):
        obj.pistil_pos = PISTIL_POS_UPDATE_FORWARDS.get(obj.pistil_pos, "")
        obj.save()


def update_blossom_pistil_pos_reverse(apps, schema_editor):
    PISTIL_POS_UPDATE_REVERSE = {
        "end": "en",
        "sei": "se",
        "gru": "gr",
        "gyn": "gy",
        "sen": "",
        "sse": "",
        "sgr": "",
        "sgy": "",
    }

    Blossom = apps.get_model("dive_content", "Blossom")

    for obj in Blossom.objects.exclude(pistil_pos=""):
        obj.pistil_pos = PISTIL_POS_UPDATE_REVERSE.get(obj.pistil_pos, "")
        obj.save()


class Migration(migrations.Migration):

    dependencies = [
        ("dive_content", "0079_bulk_alter_blossom"),
    ]

    operations = [
        migrations.RunPython(migrations.RunPython.noop, prune_blossom_merosity),
        migrations.RunPython(
            update_blossom_ovary_pos_forwards, update_blossom_ovary_pos_reverse
        ),
        migrations.RunPython(
            update_blossom_pistil_pos_forwards, update_blossom_pistil_pos_reverse
        ),
    ]
