# Generated by Django 3.0.8 on 2021-03-14 03:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("dive_content", "0079_remove_sprout_rose"),
    ]

    operations = [
        migrations.RenameField(model_name="leaf", old_name="sp_top", new_name="apex",),
        migrations.RenameField(
            model_name="leaf", old_name="pos_axis", new_name="arrangement",
        ),
        migrations.RenameField(
            model_name="leaf", old_name="att_axis", new_name="attachment",
        ),
        migrations.RenameField(
            model_name="leaf", old_name="sp_ground", new_name="base",
        ),
        migrations.RenameField(
            model_name="leaf", old_name="blade_div", new_name="blade_subdiv_shape",
        ),
        migrations.RenameField(
            model_name="leaf", old_name="blade_undiv", new_name="blade_undiv_shape",
        ),
        migrations.RenameField(
            model_name="leaf", old_name="diam", new_name="cross_section",
        ),
        migrations.RenameField(
            model_name="leaf", old_name="spr_whole", new_name="division",
        ),
        migrations.RenameField(model_name="leaf", old_name="margin", new_name="edge",),
        migrations.RenameField(
            model_name="leaf", old_name="dep_cuts", new_name="incision_depth",
        ),
        migrations.RenameField(
            model_name="leaf", old_name="cnt_germ", new_name="seed_leaf_num",
        ),
        migrations.RenameField(
            model_name="leaf", old_name="specialty", new_name="special_features",
        ),
        migrations.RenameField(
            model_name="leaf", old_name="stipule_margin", new_name="stipule_edge",
        ),
        migrations.RenameField(model_name="leaf", old_name="nerves", new_name="veins",),
    ]
