# Generated by Django 3.0.8 on 2021-04-19 23:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("dive_content", "0080_bulk_update_blossom"),
    ]

    operations = [
        migrations.RemoveField(model_name="blossom", name="chalice",),
        migrations.RemoveField(model_name="blossom", name="crown_out",),
        migrations.RemoveField(model_name="blossom", name="griffel_sub",),
        migrations.RemoveField(model_name="blossom", name="parting",),
        migrations.RemoveField(model_name="blossom", name="season_old",),
        migrations.RemoveField(model_name="blossom", name="spec_pipe",),
    ]
