# Generated by Django 3.0.8 on 2021-03-14 04:29

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("dive_content", "0080_bulk_rename_leaf_fields"),
    ]

    operations = [
        migrations.AlterField(
            model_name="leaf",
            name="arrangement",
            field=models.CharField(
                blank=True,
                choices=[
                    ("gru", "grundständig"),
                    ("wec", "wechselständig/spiralig"),
                    ("zwe", "zweizeilig/distich"),
                    ("dre", "dreizeilig/tristich"),
                    ("geg", "gegenständig"),
                    ("kre", "kreuzgegenständig/dekussiert"),
                    ("gep", "gepaart"),
                    ("qui", "quirlig/wirtelig"),
                    ("sch", "scheinquirlig"),
                    ("dac", "dachziegelig"),
                    ("ein", "einseitig"),
                    ("ges", "gescheitelt"),
                ],
                max_length=3,
                verbose_name="Anordnung (an Sprossachse)",
            ),
        ),
        migrations.AlterField(
            model_name="leaf",
            name="attachment",
            field=django.contrib.postgres.fields.ArrayField(
                base_field=models.CharField(
                    choices=[
                        ("ges", "gestielt"),
                        ("sit", "sitzend/ungestielt"),
                        ("ste", "stengelumfassend"),
                        ("hal", "halbstengelumfassend"),
                        ("dur", "durchwachsen"),
                        ("ver", "verwachsen"),
                        ("sch", "scheidig verwachsen"),
                        ("her", "herablaufend"),
                        ("rei", "reitend"),
                        ("hin", "hinfällig"),
                    ],
                    max_length=3,
                    verbose_name="Anheftung (an Sprossachse)",
                ),
                blank=True,
                default=list,
                size=2,
            ),
        ),
        migrations.AlterField(
            model_name="leaf",
            name="blade_subdiv_shape",
            field=django.contrib.postgres.fields.ArrayField(
                base_field=models.CharField(
                    choices=[
                        ("han", "handförmig"),
                        ("gef", "gefingert"),
                        ("fif", "fiederförmig"),
                        ("fil", "fiederlappig"),
                        ("fip", "fiederspaltig"),
                        ("fit", "fiederteilig"),
                        ("fis", "fiederschnittig"),
                        ("paa", "paarig"),
                        ("unp", "unpaarig"),
                        ("unt", "unterbrochen"),
                        ("dop", "doppelt"),
                        ("meh", "mehrfach"),
                        ("dre", "dreizählig"),
                        ("dod", "doppelt dreizählig"),
                        ("lei", "leierförmig"),
                        ("sch", "schrotsägeförmig"),
                        ("kam", "kammförmig"),
                        ("fus", "fußförmig"),
                    ],
                    max_length=3,
                    verbose_name="Spreitengestalt (unterteiltes Blatt)",
                ),
                blank=True,
                default=list,
                size=2,
            ),
        ),
        migrations.AlterField(
            model_name="leaf",
            name="blade_undiv_shape",
            field=django.contrib.postgres.fields.ArrayField(
                base_field=models.CharField(
                    choices=[
                        ("kre", "kreisrund"),
                        ("run", "rundlich"),
                        ("ell", "elliptisch"),
                        ("eif", "eiförmig"),
                        ("ver", "verkehrteiförmig"),
                        ("spa", "spatelförmig/spatelig"),
                        ("len", "lanzettlich"),
                        ("eil", "eilanzettlich"),
                        ("lae", "länglich"),
                        ("lin", "linealisch/lineal"),
                        ("nad", "nadelförmig"),
                        ("pfr", "pfriemlich"),
                        ("bor", "borstenförmig/borstlich"),
                        ("fad", "fadenförmig/fädlich"),
                        ("bin", "binsenartig"),
                        ("roe", "röhrig"),
                        ("ser", "schwertförmig"),
                        ("dre", "dreieckig"),
                        ("kei", "keilförmig"),
                        ("rau", "rautenförmig/rhombisch"),
                        ("her", "herzförmig"),
                        ("vhe", "verkehrtherzförmig"),
                        ("nie", "nierenförmig"),
                        ("pfe", "pfeilförmig"),
                        ("spi", "spießförmig"),
                        ("gei", "geigenförmig"),
                        ("sup", "schuppenförmig"),
                        ("sil", "schildförmig"),
                    ],
                    max_length=3,
                    verbose_name="Spreitengestalt (ungeteiltes Blatt)",
                ),
                blank=True,
                default=list,
                size=2,
            ),
        ),
        migrations.AlterField(
            model_name="leaf",
            name="division",
            field=models.CharField(
                blank=True,
                choices=[("ein", "einfach"), ("zus", "zusammengesetzt")],
                max_length=3,
                verbose_name="Spreitengliederung",
            ),
        ),
        migrations.AlterField(
            model_name="leaf",
            name="incision_depth",
            field=django.contrib.postgres.fields.ArrayField(
                base_field=models.CharField(
                    choices=[
                        ("gan", "ganz/ungeteilt"),
                        ("gel", "gelappt"),
                        ("gep", "gespalten"),
                        ("get", "geteilt"),
                        ("ges", "geschnitten"),
                        ("gef", "gefingert"),
                        ("zus", "zusammengesetzt"),
                        ("fis", "fiederschnittig"),
                        ("fie", "gefiedert"),
                    ],
                    max_length=3,
                    verbose_name="Einschnitttiefe",
                ),
                blank=True,
                default=list,
                size=2,
            ),
        ),
        migrations.AlterField(
            model_name="leaf",
            name="seed_leaf_num",
            field=models.IntegerField(
                blank=True,
                choices=[(1, 1), (2, 2)],
                null=True,
                verbose_name="Keimblattanzahl",
            ),
        ),
        migrations.AlterField(
            model_name="leaf",
            name="sheath",
            field=models.CharField(
                blank=True,
                help_text='"Nicht vorhanden" eingeben, um hervorzuheben, dass kein ausgeprägtes Merkmal existiert.',
                max_length=100,
                verbose_name="Blattscheide",
            ),
        ),
        migrations.AlterField(
            model_name="leaf",
            name="special_features",
            field=models.CharField(
                blank=True,
                help_text='"Nicht vorhanden" eingeben, um hervorzuheben, dass kein ausgeprägtes Merkmal existiert.',
                max_length=200,
                verbose_name="Besondere Merkmale",
            ),
        ),
    ]
