# Generated by Django 3.0.8 on 2021-03-21 12:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("dive_content", "0082_bulk_add_leaf_fields"),
    ]

    operations = [
        migrations.RenameField(
            model_name="fruit", old_name="type", new_name="fruit_type",
        ),
        migrations.RenameField(
            model_name="fruit", old_name="pos", new_name="ovule_pos",
        ),
        migrations.RenameField(
            model_name="fruit", old_name="form", new_name="seed_form",
        ),
        migrations.RenameField(
            model_name="fruit", old_name="cnt", new_name="seed_num",
        ),
        migrations.RenameField(
            model_name="fruit", old_name="wings", new_name="winging",
        ),
        migrations.RenameField(
            model_name="fruit", old_name="wings_spec", new_name="winging_feature",
        ),
    ]
