# Generated by Django 3.0.8 on 2021-05-01 20:45

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("dive_content", "0082_alter_blossom_merosity"),
    ]

    operations = [
        migrations.AddField(
            model_name="leaf",
            name="color",
            field=models.CharField(
                blank=True, max_length=100, verbose_name="Blattfarbe"
            ),
        ),
        migrations.AddField(
            model_name="leaf",
            name="leaf_simple_incision_depth",
            field=django.contrib.postgres.fields.ArrayField(
                base_field=models.CharField(
                    choices=[
                        ("gan", "ganz/ungeteilt"),
                        ("gel", "gelappt"),
                        ("gep", "gespalten"),
                        ("get", "geteilt"),
                        ("ges", "geschnitten"),
                    ],
                    max_length=3,
                    verbose_name="Einschnitttiefe (einf. Blatt)",
                ),
                blank=True,
                default=list,
                size=2,
            ),
        ),
        migrations.AddField(
            model_name="leaf",
            name="leaf_simple_incision_num",
            field=models.CharField(
                blank=True, max_length=10, verbose_name="Einschnittanzahl (einf. Blatt)"
            ),
        ),
    ]
