# Generated by Django 3.0.8 on 2021-05-01 21:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("dive_content", "0083_bulk_add_leaf"),
    ]

    operations = [
        migrations.RenameField(
            model_name="leaf",
            old_name="blade_subdiv_shape",
            new_name="leaf_comp_blade_shape",
        ),
        migrations.RenameField(
            model_name="leaf",
            old_name="incision_depth",
            new_name="leaf_comp_incision_depth",
        ),
        migrations.RenameField(
            model_name="leaf",
            old_name="incision_num",
            new_name="leaf_comp_incision_num",
        ),
        migrations.RenameField(
            model_name="leaf",
            old_name="blade_undiv_shape",
            new_name="leaf_simple_blade_shape",
        ),
    ]
