# Generated by Django 3.0.8 on 2021-03-21 13:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("dive_content", "0084_bulk_alter_fruit_fields"),
    ]

    operations = [
        migrations.AddField(
            model_name="fruit",
            name="fruit_form",
            field=models.CharField(
                blank=True, max_length=100, verbose_name="Fruchtform"
            ),
        ),
    ]
