# Generated by Django 3.0.8 on 2021-05-01 22:48

from django.db import migrations


def prune_leaf_surface(apps, schema_editor):
    Leaf = apps.get_model("dive_content", "Leaf")

    for obj in Leaf.objects.exclude(surface=[]):
        for opt in ("stn", "glz"):
            if opt in obj.surface:
                obj.surface.remove(opt)
                obj.save()


def prune_stemroot_surface(apps, schema_editor):
    StemRoot = apps.get_model("dive_content", "StemRoot")

    for obj in StemRoot.objects.exclude(surface=[]):
        for opt in ("stn", "glz"):
            if opt in obj.surface:
                obj.surface.remove(opt)
                obj.save()


class Migration(migrations.Migration):

    dependencies = [
        ("dive_content", "0085_bulk_alter_leaf_and_stemroot"),
    ]

    operations = [
        migrations.RunPython(migrations.RunPython.noop, prune_leaf_surface),
        migrations.RunPython(migrations.RunPython.noop, prune_stemroot_surface),
    ]
