# Generated by Django 3.0.8 on 2021-05-02 01:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("dive_content", "0087_rename_fruit_seed_form"),
    ]

    operations = [
        migrations.AlterField(
            model_name="fruit",
            name="seed_color_form",
            field=models.CharField(
                blank=True,
                help_text="Alles ausschreiben.",
                max_length=100,
                verbose_name="Farbe/Form (Samen)",
            ),
        ),
    ]
