# Generated by Django 3.0.8 on 2021-05-02 02:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("dive_content", "0088_alter_fruit_seed_color_form"),
    ]

    operations = [
        migrations.AddField(
            model_name="stemroot",
            name="pith",
            field=models.CharField(
                blank=True,
                choices=[("h", "hohl"), ("m", "markig")],
                max_length=1,
                verbose_name="Mark",
            ),
        ),
    ]
