# Generated by Django 3.0.8 on 2021-05-02 02:37

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("dive_content", "0089_add_stemroot_pith"),
    ]

    operations = [
        migrations.AlterField(
            model_name="stemroot",
            name="cross_section",
            field=django.contrib.postgres.fields.ArrayField(
                base_field=models.CharField(
                    choices=[
                        ("sti", "stielrund"),
                        ("hal", "halbstielrund"),
                        ("zus", "zusammengedrückt"),
                        ("zwe", "zweischneidig"),
                        ("kan", "kantig"),
                        ("stu", "stumpfkantig"),
                        ("ger", "gerieft/gerillt"),
                        ("gef", "gefurcht"),
                        ("kgs", "kantig gefurcht/scharfkantig"),
                        ("gri", "gerippt"),
                        ("gfl", "geflügelt"),
                        ("kno", "knotig"),
                    ],
                    max_length=3,
                    verbose_name="Querschnitt",
                ),
                blank=True,
                default=list,
                size=2,
            ),
        ),
    ]
