# Generated by Django 3.0.8 on 2021-05-02 02:40

from django.db import migrations


def prune_stemroot_cross_section(apps, schema_editor):
    StemRoot = apps.get_model("dive_content", "StemRoot")

    for obj in StemRoot.objects.exclude(cross_section=[]):
        if "kgs" in obj.cross_section:
            obj.cross_section.remove("kgs")
            obj.save()


class Migration(migrations.Migration):

    dependencies = [
        ("dive_content", "0090_alter_stemroot_cross_section"),
    ]

    operations = [
        migrations.RunPython(migrations.RunPython.noop, prune_stemroot_cross_section),
    ]
