# Generated by Django 3.0.8 on 2021-05-02 14:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("dive_content", "0093_update_blossom_carpel_connation_type"),
    ]

    operations = [
        migrations.AddField(
            model_name="plant",
            name="article",
            field=models.CharField(
                blank=True,
                choices=[("der", "Der"), ("die", "Die"), ("das", "Das")],
                max_length=3,
                verbose_name="Artikel",
            ),
        ),
        migrations.AddField(
            model_name="plant",
            name="other_features",
            field=models.CharField(
                blank=True,
                help_text="Bsp. Geruch",
                max_length=200,
                verbose_name="Weitere Merkmale",
            ),
        ),
    ]
