# Generated by Django 3.0.8 on 2021-05-02 18:17

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("dive_content", "0094_bulk_add_plant"),
    ]

    operations = [
        migrations.AlterField(
            model_name="plant",
            name="dispersal",
            field=models.CharField(
                blank=True,
                choices=[
                    ("na", "Nacktsamer"),
                    ("be", "Bedecktsamer"),
                    ("sp", "Sporenpflanze"),
                ],
                max_length=2,
                verbose_name="Ausbreitungsform",
            ),
        ),
        migrations.AlterField(
            model_name="plant",
            name="growth_form",
            field=models.CharField(
                blank=True,
                choices=[
                    ("bau", "Baum"),
                    ("str", "Strauch"),
                    ("stb", "Strauchbaum"),
                    ("zwe", "Zwergstrauch"),
                    ("hal", "Halbstrauch"),
                    ("spa", "Spalierstrauch"),
                    ("scs", "Scheinstrauch"),
                    ("sta", "Staudenstrauch"),
                    ("kra", "Kraut"),
                    ("krc", "krautiger Chemaephyt"),
                    ("lia", "Liane"),
                    ("kle", "Kletterpflanze"),
                    ("tau", "Tauchpflanze"),
                    ("sch", "Schwimmpflanze"),
                ],
                max_length=3,
                verbose_name="Wuchsform",
            ),
        ),
        migrations.AlterField(
            model_name="plant",
            name="habitat",
            field=django.contrib.postgres.fields.ArrayField(
                base_field=models.CharField(
                    choices=[
                        ("sch", "Schlammflure"),
                        ("roe", "Röhrichte"),
                        ("sae", "Säume"),
                        ("sta", "Staudenflure"),
                        ("gru", "Grünland"),
                        ("zwe", "Zwergstrauchheiden"),
                        ("rud", "Ruderalvegetationen"),
                        ("aec", "Äcker"),
                        ("wei", "Weinberge"),
                        ("int", "Intensivgrünland"),
                        ("par", "Parks"),
                        ("gae", "Gärten"),
                        ("tri", "Trittpflanzengesellschaften"),
                        ("fel", "Felsbiotope"),
                        ("aue", "Auenwälder"),
                        ("geb", "Gebüsche"),
                        ("ger", "Gerölle"),
                        ("ext", "Extensivgrünland"),
                        ("nar", "natürliche Rasen"),
                        ("wae", "Wälder"),
                        ("ufe", "Ufer"),
                        ("wed", "Weiden"),
                        ("wie", "Wiesen"),
                        ("hec", "Hecken"),
                        ("gra", "Gräben"),
                        ("weg", "Weg-/Straßenränder"),
                        ("bah", "Bahndämme"),
                        ("bae", "Bäche"),
                        ("sct", "Schutt"),
                        ("brw", "Bruchwälder"),
                        ("que", "Quellen"),
                        ("scl", "Schläge"),
                    ],
                    max_length=3,
                    verbose_name="Habitat",
                ),
                blank=True,
                size=None,
            ),
        ),
        migrations.AlterField(
            model_name="plant",
            name="life_form",
            field=models.CharField(
                blank=True,
                choices=[
                    ("pha", "Phanerophyt"),
                    ("cha", "Chamaephyt"),
                    ("hem", "Hemikryptophyt"),
                    ("kry", "Kryptophyt"),
                    ("the", "Therophyt"),
                    ("geo", "Geophyt"),
                    ("hel", "Helophyt (Sumpfpflanze)"),
                    ("hyd", "Hydrophyt (Wasserpflanze)"),
                ],
                max_length=3,
                verbose_name="Lebensform",
            ),
        ),
    ]
