# Generated by Django 3.0.8 on 2021-05-02 16:58

from django.db import migrations


def prune_plant_habitat(apps, schema_editor):
    Plant = apps.get_model("dive_content", "Plant")

    for obj in Plant.objects.exclude(habitat=[]):
        for opt in (
            "zwe",
            "nar",
            "wed",
            "wie",
            "hec",
            "gra",
            "weg",
            "bah",
            "bae",
            "sct",
            "brw",
            "que",
            "scl",
        ):
            if opt in obj.habitat:
                obj.habitat.remove(opt)
                obj.save()


def prune_plant_life_form(apps, schema_editor):
    Plant = apps.get_model("dive_content", "Plant")

    for obj in Plant.objects.exclude(life_form=""):
        if obj.life_form in ("geo", "hel", "hyd"):
            obj.life_form = ""
            obj.save()


def prune_plant_growth_form_forwards(apps, schema_editor):
    Plant = apps.get_model("dive_content", "Plant")

    for obj in Plant.objects.exclude(growth_form=""):
        if obj.growth_form in ("geo", "hel", "hyd"):
            obj.growth_form = ""
            obj.save()


def prune_plant_growth_form_reverse(apps, schema_editor):
    Plant = apps.get_model("dive_content", "Plant")

    for obj in Plant.objects.exclude(growth_form=""):
        if obj.growth_form in ("kra", "scs", "sta"):
            obj.growth_form = ""
            obj.save()


def prune_plant_dispersal_forwards(apps, schema_editor):
    Plant = apps.get_model("dive_content", "Plant")

    for obj in Plant.objects.exclude(dispersal=""):
        if obj.dispersal == "sa":
            obj.dispersal = ""
            obj.save()


def prune_plant_dispersal_reverse(apps, schema_editor):
    Plant = apps.get_model("dive_content", "Plant")

    for obj in Plant.objects.exclude(dispersal=""):
        if obj.dispersal in ("na", "be"):
            obj.dispersal = ""
            obj.save()


class Migration(migrations.Migration):

    dependencies = [
        ("dive_content", "0095_bulk_alter_plant"),
    ]

    operations = [
        migrations.RunPython(migrations.RunPython.noop, prune_plant_habitat),
        migrations.RunPython(migrations.RunPython.noop, prune_plant_life_form),
        migrations.RunPython(
            prune_plant_growth_form_forwards, prune_plant_growth_form_reverse
        ),
        migrations.RunPython(
            prune_plant_dispersal_forwards, prune_plant_dispersal_reverse
        ),
    ]
