# Generated by Django 3.0.8 on 2021-09-13 07:19

import django.contrib.postgres.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("dive_content", "0096_bulk_update_plant"),
    ]

    operations = [
        migrations.CreateModel(
            name="LeafPoales",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "length",
                    models.CharField(blank=True, max_length=20, verbose_name="Länge"),
                ),
                (
                    "width",
                    models.CharField(
                        blank=True,
                        help_text="Bsp. 2–4(–6) mm",
                        max_length=50,
                        verbose_name="Breite",
                    ),
                ),
                (
                    "color",
                    models.CharField(
                        blank=True,
                        help_text="Grammatikalisch anpassen.",
                        max_length=50,
                        verbose_name="Farbe",
                    ),
                ),
                (
                    "shape",
                    models.CharField(
                        blank=True,
                        choices=[("f", "flach"), ("r", "röhrig")],
                        max_length=1,
                        verbose_name="Form",
                    ),
                ),
                (
                    "hairiness",
                    django.contrib.postgres.fields.ArrayField(
                        base_field=models.CharField(
                            choices=[
                                ("kah", "kahl"),
                                ("sam", "samtig"),
                                ("lob", "locker behaart"),
                                ("beh", "behaart"),
                                ("dib", "dicht behaart"),
                                ("wol", "wollig"),
                            ],
                            max_length=3,
                        ),
                        blank=True,
                        default=list,
                        size=2,
                        verbose_name="Behaarung",
                    ),
                ),
                (
                    "cross_section",
                    django.contrib.postgres.fields.ArrayField(
                        base_field=models.CharField(
                            choices=[
                                ("Voa", "Vogelflug-artig"),
                                ("VPa", "V-Profil-artig"),
                                ("UPa", "U-Profil-artig"),
                                ("roe", "röhrig"),
                                ("run", "rund"),
                                ("abg", "abgeflacht"),
                                ("fla", "flach"),
                                ("bor", "borstig"),
                            ],
                            max_length=3,
                        ),
                        blank=True,
                        default=list,
                        size=2,
                        verbose_name="Querschnitt",
                    ),
                ),
                (
                    "alignment",
                    models.CharField(
                        blank=True, max_length=3, verbose_name="Ausrichtung"
                    ),
                ),
                (
                    "attachment_point",
                    models.CharField(
                        blank=True,
                        choices=[("K", "Knoten"), ("T", "Triebgrund")],
                        max_length=1,
                        verbose_name="Ansatzstelle",
                    ),
                ),
                (
                    "blade_shape",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("bor", "borstenförmig"),
                            ("lan", "lanzettlich"),
                            ("lin", "linealisch"),
                            ("par", "parallelrandig"),
                            ("pfr", "pfriemlich"),
                        ],
                        max_length=3,
                        verbose_name="Form",
                    ),
                ),
                (
                    "blade_shape_feature",
                    models.CharField(
                        blank=True, max_length=50, verbose_name="Besonderheit (Form)"
                    ),
                ),
                (
                    "blade_corrugation",
                    django.contrib.postgres.fields.ArrayField(
                        base_field=models.CharField(
                            choices=[
                                ("gla", "glatt"),
                                ("gmS", "glatt mit Skispur"),
                                ("ung", "undeutlich gerieft"),
                                ("deg", "deutlich gerieft"),
                                ("ssg", "sehr stark gerieft"),
                            ],
                            max_length=3,
                        ),
                        blank=True,
                        default=list,
                        size=2,
                        verbose_name="Riefung",
                    ),
                ),
                (
                    "blade_double_groove",
                    models.CharField(
                        blank=True,
                        choices=[("m", "mit Doppelrille"), ("o", "ohne Doppelrille")],
                        max_length=1,
                        verbose_name="Doppelrille",
                    ),
                ),
                (
                    "blade_shine",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("gla", "glanzlos"),
                            ("mag", "matt glänzend"),
                            ("seg", "seidig glänzend"),
                            ("stg", "stark glänzend"),
                        ],
                        max_length=3,
                        verbose_name="Glanz",
                    ),
                ),
                (
                    "blade_keel",
                    models.CharField(
                        blank=True,
                        choices=[("m", "mit auffälligem Kiel"), ("o", "ohne Kiel")],
                        max_length=1,
                        verbose_name="Kiel",
                    ),
                ),
                (
                    "blade_edge",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("gla", "glatt"),
                            ("vor", "vorwärts rau"),
                            ("rur", "rückwärts rau"),
                            ("bew", "bewimpert"),
                            ("bor", "borstig"),
                            ("gez", "gezähnt"),
                        ],
                        max_length=3,
                        verbose_name="Rand",
                    ),
                ),
                (
                    "blade_bud_system",
                    models.CharField(
                        blank=True,
                        choices=[("f", "gefaltet"), ("r", "gerollt")],
                        max_length=1,
                        verbose_name="Knospenanlage",
                    ),
                ),
                (
                    "base_edge",
                    models.CharField(
                        blank=True,
                        choices=[("k", "kahl"), ("b", "behaart (< 3 mm)")],
                        max_length=1,
                        verbose_name="Rand",
                    ),
                ),
                (
                    "base_auricle",
                    models.CharField(
                        blank=True,
                        choices=[("m", "mit Öhrchen"), ("o", "ohne Öhrchen")],
                        max_length=1,
                        verbose_name="Öhrchen",
                    ),
                ),
                (
                    "base_auricle_feature",
                    models.CharField(
                        blank=True, max_length=50, verbose_name="Besonderheit (Öhrchen)"
                    ),
                ),
                (
                    "ligule_length",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("kur", "kurz"),
                            ("mit", "mittellang"),
                            ("lan", "lang"),
                            ("sel", "sehr lang"),
                        ],
                        max_length=3,
                        verbose_name="Länge",
                    ),
                ),
                (
                    "ligule_color",
                    models.CharField(
                        blank=True,
                        help_text="Grammatikalisch anpassen.",
                        max_length=50,
                        verbose_name="Farbe",
                    ),
                ),
                (
                    "ligule_shape",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("abg", "abgerundet"),
                            ("aHa", "als Haarkranz ausgebildet"),
                            ("bew", "bewimpert"),
                            ("feh", "fehlend"),
                            ("ges", "geschlitzt"),
                            ("man", "manschettenförmig"),
                            ("roe", "röhrenförmig"),
                            ("sau", "saumartig"),
                            ("spi", "spitz"),
                            ("stu", "stumpf"),
                            ("zer", "zerschlitzt"),
                        ],
                        max_length=3,
                        verbose_name="Form",
                    ),
                ),
                (
                    "ligule_consistency",
                    models.CharField(
                        blank=True,
                        choices=[("der", "derb"), ("hae", "häutig"), ("zar", "zart")],
                        max_length=3,
                        verbose_name="Konsistenz",
                    ),
                ),
                (
                    "ligule_features",
                    models.CharField(
                        blank=True,
                        help_text="Als eigenständigen Satz ausformulieren.",
                        max_length=100,
                        verbose_name="Besonderheiten",
                    ),
                ),
                (
                    "sheath_coloring",
                    models.CharField(
                        blank=True,
                        help_text="Grammatikalisch anpassen.",
                        max_length=50,
                        verbose_name="Färbung",
                    ),
                ),
                (
                    "sheath_connation",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("off", "offen"),
                            ("iTv", "in Teilen verwachsen"),
                            ("fbo", "fast bis oben geschlossen"),
                            ("ges", "geschlossen"),
                        ],
                        max_length=3,
                        verbose_name="Verwachsung",
                    ),
                ),
                (
                    "sheath_features",
                    models.CharField(
                        blank=True,
                        help_text="Als eigenständigen Satz ausformulieren.",
                        max_length=100,
                        verbose_name="Besonderheiten",
                    ),
                ),
                (
                    "plant",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="leafpoales",
                        to="dive_content.Plant",
                        verbose_name="Pflanze",
                    ),
                ),
            ],
            options={
                "verbose_name": "Blatt (Poales)",
                "verbose_name_plural": "Blätter (Poales)",
            },
        ),
    ]
