# Generated by Django 3.0.8 on 2021-09-13 07:10

import django.contrib.postgres.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("dive_content", "0097_create_leafpoales"),
    ]

    operations = [
        migrations.CreateModel(
            name="BlossomPoales",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "season",
                    django.contrib.postgres.fields.ArrayField(
                        base_field=models.IntegerField(blank=True, null=True),
                        blank=True,
                        default=list,
                        size=4,
                        verbose_name="Blütezeit",
                    ),
                ),
                (
                    "inflorescence_blossom_number",
                    models.CharField(
                        blank=True, max_length=20, verbose_name="Blütenanzahl"
                    ),
                ),
                (
                    "inflorescence_density",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("l", "locker"),
                            ("d", "in dichten Kopf zusammengezogen"),
                        ],
                        max_length=1,
                        verbose_name="Dichte",
                    ),
                ),
                (
                    "inflorescence_position",
                    models.CharField(
                        blank=True,
                        choices=[("a", "aufrecht"), ("s", "scheinbar seitenständig")],
                        max_length=1,
                        verbose_name="Stellung",
                    ),
                ),
                (
                    "inflorescence_type",
                    models.CharField(
                        blank=True,
                        choices=[("A", "Ähre"), ("R", "Rispe"), ("S", "Spirre")],
                        max_length=1,
                        verbose_name="Typ",
                    ),
                ),
                (
                    "inflorescence_features",
                    models.CharField(
                        blank=True, max_length=50, verbose_name="Besonderheiten"
                    ),
                ),
                (
                    "inflorescence_bract_length",
                    models.CharField(
                        blank=True, max_length=20, verbose_name="Tragblattlänge"
                    ),
                ),
                (
                    "inflorescence_bract_feature",
                    models.CharField(
                        blank=True,
                        max_length=50,
                        verbose_name="Besonderheit (Tragblatt)",
                    ),
                ),
                (
                    "blossom_sex",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("z", "zwittrig"),
                            ("s", "zwittrig, selten einige weiblich"),
                            ("e", "eingeschlechtig"),
                        ],
                        max_length=1,
                        verbose_name="Geschlecht",
                    ),
                ),
                (
                    "perianth",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("m", "mit Blütenhülle"),
                            ("S", "Blüte von Spelzen umgeben"),
                        ],
                        max_length=1,
                        verbose_name="Blütenhülle",
                    ),
                ),
                (
                    "blossom_description",
                    models.TextField(
                        blank=True,
                        help_text="Mit eigenständigem Satzbau ausformulieren.",
                        max_length=200,
                        verbose_name="Blüte (Beschreibung)",
                    ),
                ),
                (
                    "perianth_description",
                    models.TextField(
                        blank=True,
                        help_text="Mit eigenständigem Satzbau ausformulieren.",
                        max_length=200,
                        verbose_name="Blütenhülle (Beschreibung)",
                    ),
                ),
                (
                    "spikelet_length",
                    models.CharField(blank=True, max_length=20, verbose_name="Länge"),
                ),
                (
                    "spikelet_shape",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("zSv", "zur Spitze hin verbreitert"),
                            ("zus", "zusammengedrückt"),
                            ("sez", "seitlich zusammengedrückt"),
                            ("niz", "nicht zusammengedrückt"),
                        ],
                        max_length=3,
                        verbose_name="Form",
                    ),
                ),
                (
                    "spikelet_attachment",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("ges", "gestielt"),
                            ("bog", "borstenlos gestielt"),
                            ("vou", "völlig ungestielt"),
                            ("sit", "sitzend"),
                        ],
                        max_length=3,
                        verbose_name="Ansatz",
                    ),
                ),
                (
                    "spikelet_sex",
                    models.CharField(
                        blank=True,
                        choices=[("z", "zwittrig"), ("e", "eingeschlechtig")],
                        max_length=1,
                        verbose_name="Geschlecht",
                    ),
                ),
                (
                    "spikelet_blossom_number",
                    models.CharField(
                        blank=True, max_length=20, verbose_name="Blütenanzahl"
                    ),
                ),
                (
                    "spikelet_max_width",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("un", "unter der Mitte"),
                            ("in", "in der Mitte"),
                            ("ue", "über der Mitte"),
                        ],
                        max_length=2,
                        verbose_name="Breitenmaxium",
                    ),
                ),
                (
                    "spikelet_rachilla",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("gBa", "glatt, zur Blütezeit abstehend"),
                            ("sic", "sichtbar"),
                            ("zRs", "zur Reife sichtbar"),
                            ("nis", "nicht sichtbar"),
                        ],
                        max_length=3,
                        verbose_name="Achse",
                    ),
                ),
                (
                    "spikelet_stalk",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("lau", "lang, unverzweigt"),
                            ("lav", "lang, verzweigt"),
                            ("kur", "kurz"),
                            ("skv", "sehr kurz, verzweigt"),
                            ("vkA", "viel kürzer als Ährchen"),
                        ],
                        max_length=3,
                        verbose_name="Stiel",
                    ),
                ),
                (
                    "spikelet_spindle",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("z", "zerbrechlich"),
                            ("B", "nach der Blütezeit zerbrechlich"),
                            ("n", "nicht zerbrechlich"),
                        ],
                        max_length=1,
                        verbose_name="Spindel",
                    ),
                ),
                (
                    "spikelet_features",
                    models.CharField(
                        blank=True,
                        help_text="Als eigenständigen Satz ausformulieren.",
                        max_length=100,
                        verbose_name="Besonderheiten",
                    ),
                ),
                (
                    "husks_form",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("a", "abgerundet"),
                            ("R", "auf dem Rücken abgerundet"),
                            ("n", "nicht abgerundet"),
                        ],
                        max_length=1,
                        verbose_name="Form",
                    ),
                ),
                (
                    "husks_keel",
                    models.CharField(
                        blank=True,
                        choices=[("g", "gekielt"), ("n", "nicht gekielt")],
                        max_length=1,
                        verbose_name="Kiel",
                    ),
                ),
                (
                    "husks_cross_section",
                    django.contrib.postgres.fields.ArrayField(
                        base_field=models.CharField(
                            choices=[
                                ("o", "oval"),
                                ("r", "rundlich"),
                                ("s", "2-schneidig"),
                            ],
                            max_length=1,
                        ),
                        blank=True,
                        default=list,
                        size=2,
                        verbose_name="Querschnitt",
                    ),
                ),
                (
                    "husks_description",
                    models.TextField(
                        blank=True,
                        help_text="Mit eigenständigem Satzbau ausformulieren.",
                        max_length=400,
                        verbose_name="Beschreibung",
                    ),
                ),
                (
                    "plant",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="blossompoales",
                        to="dive_content.Plant",
                        verbose_name="Pflanze",
                    ),
                ),
            ],
            options={
                "verbose_name": "Blüte (Poales)",
                "verbose_name_plural": "Blüten (Poales)",
            },
        ),
    ]
