# Generated by Django 3.0.8 on 2021-09-07 09:53

from django.db import migrations


def populate_plant_alternative_trivial_names_with_alt_trivial_name(apps, schema_editor):
    """
    Populate Plant model alternative_trivial_names fields with alt_trivial_name values.
    """
    Plant = apps.get_model("dive_content", "Plant")

    for obj in Plant.objects.all():
        if obj.alt_trivial_name:
            obj.alternative_trivial_names = [
                f"{x[:50]}" for x in obj.alt_trivial_name.split(", ")[:4]
            ]
        else:
            obj.alternative_trivial_names = []
        obj.save()


def populate_plant_alt_trivial_name_with_alternative_trivial_names(apps, schema_editor):
    """
    Populate Plant model alt_trivial_name with alternative_trivial_names values.
    """
    Plant = apps.get_model("dive_content", "Plant")

    for obj in Plant.objects.all():
        if obj.alternative_trivial_names:
            obj.alt_trivial_name = ", ".join(obj.alternative_trivial_names)
        else:
            obj.alt_trivial_name = ""
        obj.save()


class Migration(migrations.Migration):

    dependencies = [
        ("dive_content", "0101_bulk_add_plant"),
    ]

    operations = [
        migrations.RunPython(
            populate_plant_alternative_trivial_names_with_alt_trivial_name,
            populate_plant_alt_trivial_name_with_alternative_trivial_names,
        ),
    ]
