# Generated by Django 3.0.8 on 2021-12-13 15:46

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("dive_content", "0103_update_plant_growth_height"),
    ]

    operations = [
        migrations.AlterField(
            model_name="plant",
            name="article",
            field=models.CharField(
                blank=True,
                choices=[("", "-"), ("der", "der"), ("die", "die"), ("das", "das")],
                max_length=3,
                verbose_name="Artikel",
            ),
        ),
        migrations.AlterField(
            model_name="plant",
            name="ground_to_be_removed",
            field=django.contrib.postgres.fields.ArrayField(
                base_field=models.CharField(
                    choices=[
                        ("leh", "lehmig"),
                        ("tor", "torfig"),
                        ("san", "sandig"),
                        ("ste", "steinig/felsig"),
                    ],
                    max_length=3,
                    verbose_name="Untergrund",
                ),
                blank=True,
                default=list,
                size=2,
            ),
        ),
        migrations.AlterField(
            model_name="plant",
            name="growth_form",
            field=models.CharField(
                blank=True,
                choices=[
                    ("bau", "Baum"),
                    ("hal", "Halbstrauch"),
                    ("kle", "Kletterpflanze"),
                    ("kra", "Kraut"),
                    ("krc", "krautiger Chemaephyt"),
                    ("lia", "Liane"),
                    ("scs", "Scheinstrauch"),
                    ("sch", "Schwimmpflanze"),
                    ("spa", "Spalierstrauch"),
                    ("spr", "Spreizklimmer"),
                    ("sta", "Staudenstrauch"),
                    ("str", "Strauch"),
                    ("stb", "Strauchbaum"),
                    ("tau", "Tauchpflanze"),
                    ("zwe", "Zwergstrauch"),
                ],
                max_length=3,
                verbose_name="Wuchsform",
            ),
        ),
        migrations.AlterField(
            model_name="plant",
            name="growth_height",
            field=models.CharField(blank=True, max_length=20, verbose_name="Wuchshöhe"),
        ),
        migrations.AlterField(
            model_name="plant",
            name="habitat",
            field=django.contrib.postgres.fields.ArrayField(
                base_field=models.CharField(
                    choices=[
                        ("sch", "Schlammflure"),
                        ("roe", "Röhrichte"),
                        ("sae", "Säume"),
                        ("sta", "Staudenflure"),
                        ("gru", "Grünland"),
                        ("zwe", "Zwergstrauchheiden"),
                        ("rud", "Ruderalvegetationen"),
                        ("aec", "Äcker"),
                        ("wei", "Weinberge"),
                        ("int", "Intensivgrünland"),
                        ("par", "Parks"),
                        ("gae", "Gärten"),
                        ("tri", "Trittpflanzengesellschaften"),
                        ("fel", "Felsbiotope"),
                        ("aue", "Auenwälder"),
                        ("geb", "Gebüsche"),
                        ("ger", "Gerölle"),
                        ("ext", "Extensivgrünland"),
                        ("nar", "natürliche Rasen"),
                        ("wae", "Wälder"),
                        ("ufe", "Ufer"),
                        ("wed", "Weiden"),
                        ("wie", "Wiesen"),
                        ("hec", "Hecken"),
                        ("gra", "Gräben"),
                        ("weg", "Weg-/Straßenränder"),
                        ("bah", "Bahndämme"),
                        ("bae", "Bäche"),
                        ("sct", "Schutt"),
                        ("brw", "Bruchwälder"),
                        ("que", "Quellen"),
                        ("scl", "Schläge"),
                    ],
                    max_length=3,
                    verbose_name="Habitat",
                ),
                blank=True,
                default=list,
                size=None,
            ),
        ),
        migrations.AlterField(
            model_name="plant",
            name="interaction",
            field=models.CharField(
                blank=True,
                choices=[
                    ("par", "parasitisch"),
                    ("nip", "nicht parasitisch"),
                    ("obl", "obligat Mykorrhiza-bildend"),
                    ("fak", "fakultativ Mykorrhiza-bildend"),
                ],
                max_length=3,
                verbose_name="Interaktion",
            ),
        ),
        migrations.AlterField(
            model_name="plant",
            name="name",
            field=models.CharField(
                help_text="Markdown", max_length=100, verbose_name="Art"
            ),
        ),
        migrations.AlterField(
            model_name="plant",
            name="other_features",
            field=models.CharField(
                blank=True,
                help_text="Als eigenständigen Satz ausformulieren.",
                max_length=200,
                verbose_name="Weitere Merkmale",
            ),
        ),
        migrations.AlterField(
            model_name="plant",
            name="short_description",
            field=models.TextField(
                blank=True,
                default="",
                help_text="Markdown",
                max_length=600,
                verbose_name="Kurzbeschreibung",
            ),
        ),
        migrations.AlterField(
            model_name="plant",
            name="trivial_name",
            field=models.CharField(max_length=50, verbose_name="Trivialname"),
        ),
    ]
