# Generated by Django 3.0.8 on 2021-12-13 15:54

from django.db import migrations


def prune_plant_growth_form(apps, schema_editor):
    Plant = apps.get_model("dive_content", "Plant")

    for obj in Plant.objects.exclude(growth_form=""):
        if obj.growth_form == "spr":
            obj.growth_form = ""
            obj.save()


class Migration(migrations.Migration):

    dependencies = [
        ("dive_content", "0104_bulk_alter_plant"),
    ]

    operations = [
        migrations.RunPython(migrations.RunPython.noop, prune_plant_growth_form),
    ]
