# Generated by Django 3.0.8 on 2021-12-15 13:45

import django.contrib.postgres.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("dive_content", "0107_rename_plant_dispersal"),
    ]

    operations = [
        migrations.CreateModel(
            name="InterestingFacts",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "pollination",
                    django.contrib.postgres.fields.ArrayField(
                        base_field=models.CharField(
                            choices=[
                                ("Ins", "Insektenbestäubung"),
                                ("Sel", "Selbstbestäubung"),
                                ("Was", "Wasserbestäubung"),
                                ("Win", "Windbestäubung"),
                            ],
                            max_length=3,
                        ),
                        blank=True,
                        default=list,
                        size=None,
                        verbose_name="Bestäubung",
                    ),
                ),
                (
                    "insects",
                    models.CharField(
                        blank=True,
                        help_text="Zusatzangabe zur Insektenbestäubung",
                        max_length=100,
                        verbose_name="Insekten",
                    ),
                ),
                (
                    "dispersal",
                    django.contrib.postgres.fields.ArrayField(
                        base_field=models.CharField(
                            choices=[
                                ("Men", "Menschenausbreitung"),
                                ("Sel", "Selbstausbreitung"),
                                ("Sto", "Stoß-/Schüttelausbreitung"),
                                ("Ved", "Verdauungsausbreitung"),
                                ("Ves", "Versteck- u. Verlustausbreitung"),
                                ("Was", "Wasserausbreitung"),
                                ("Win", "Windausbreitung"),
                            ],
                            max_length=3,
                        ),
                        blank=True,
                        default=list,
                        size=None,
                        verbose_name="Ausbreitung",
                    ),
                ),
                (
                    "detail_features",
                    models.CharField(
                        blank=True,
                        help_text="Als eigenständigen Satz ausformulieren.",
                        max_length=200,
                        verbose_name="Detailierte Merkmale",
                    ),
                ),
                (
                    "usage",
                    models.CharField(
                        blank=True,
                        help_text="Als eigenständigen Satz ausformulieren. Markdown",
                        max_length=200,
                        verbose_name="Verwendung",
                    ),
                ),
                (
                    "trivia",
                    models.TextField(
                        blank=True,
                        help_text="Mit eigenständigem Satzbau ausformulieren. Markdown",
                        max_length=600,
                        verbose_name="Trivia",
                    ),
                ),
                (
                    "plant",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="interestingfacts",
                        to="dive_content.Plant",
                        verbose_name="Pflanze",
                    ),
                ),
            ],
            options={
                "verbose_name": "Wissenswertes",
                "verbose_name_plural": "Wissenswertes",
            },
        ),
    ]
