# Generated by Django 3.0.8 on 2022-01-02 14:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("dive_content", "0108_create_interestingfacts"),
    ]

    operations = [
        migrations.RemoveField(model_name="blossom", name="aer_per_ab",),
        migrations.RemoveField(model_name="blossom", name="aer_per_aer",),
        migrations.RemoveField(model_name="blossom", name="blos",),
        migrations.RemoveField(model_name="blossom", name="cons_top",),
        migrations.RemoveField(model_name="blossom", name="grann_form",),
        migrations.RemoveField(model_name="blossom", name="grann_top",),
        migrations.RemoveField(model_name="blossom", name="gull_spel",),
        migrations.RemoveField(model_name="blossom", name="order",),
        migrations.RemoveField(model_name="blossom", name="straw_ground",),
    ]
