# Generated by Django 3.0.8 on 2022-01-13 23:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("dive_content", "0112_bulk_update_blossom"),
    ]

    operations = [
        migrations.AddField(
            model_name="blossom",
            name="blossom_sex_distribution",
            field=models.CharField(
                blank=True,
                choices=[("e", "eingeschlechtig"), ("s", "steril"), ("z", "zwittrig")],
                max_length=1,
                verbose_name="Geschlechtigkeit",
            ),
        ),
        migrations.AddField(
            model_name="blossom",
            name="blossom_sex_distribution_addition",
            field=models.CharField(
                blank=True, max_length=100, verbose_name="Geschlechtigkeitzusatz"
            ),
        ),
        migrations.AddField(
            model_name="blossom",
            name="ovary_number",
            field=models.CharField(
                blank=True, max_length=10, verbose_name="Fruchtknotenanzahl"
            ),
        ),
        migrations.AddField(
            model_name="blossom",
            name="pistil_number",
            field=models.CharField(
                blank=True, max_length=10, verbose_name="Griffelanzahl"
            ),
        ),
        migrations.AddField(
            model_name="blossom",
            name="plant_sex_distribution",
            field=models.CharField(
                blank=True,
                choices=[
                    ("e", "einhäusig"),
                    ("u", "unvollständig zweihäusig"),
                    ("z", "zweihäusig"),
                ],
                max_length=1,
                verbose_name="Häusigkeit",
            ),
        ),
        migrations.AddField(
            model_name="blossom",
            name="specifications",
            field=models.TextField(
                blank=True,
                help_text="Mit eigenständigem Satzbau ausformulieren.",
                max_length=600,
                verbose_name="Spezifikationen",
            ),
        ),
        migrations.AddField(
            model_name="blossom",
            name="tepal_color_shape",
            field=models.CharField(
                blank=True,
                help_text="Grammatikalisch anpassen.",
                max_length=100,
                verbose_name="Farbe/Gestalt",
            ),
        ),
        migrations.AddField(
            model_name="blossom",
            name="tepal_connation",
            field=models.CharField(
                blank=True,
                choices=[
                    ("a", "am Grund verwachsen"),
                    ("u", "unverwachsen"),
                    ("v", "verwachsen"),
                ],
                max_length=1,
                verbose_name="Verwachsung",
            ),
        ),
        migrations.AddField(
            model_name="blossom",
            name="tepal_connation_type",
            field=models.CharField(
                blank=True, max_length=3, verbose_name="Verwachsungstyp"
            ),
        ),
        migrations.AddField(
            model_name="blossom",
            name="tepal_number",
            field=models.CharField(blank=True, max_length=10, verbose_name="Anzahl"),
        ),
    ]
