# Generated by Django 3.0.8 on 2022-01-14 03:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("dive_content", "0113_bulk_add_blossom"),
    ]

    operations = [
        migrations.RenameField(
            model_name="fruit", old_name="fruit_form", new_name="fruit_color_shape",
        ),
        migrations.RenameField(
            model_name="fruit", old_name="ovule_pos", new_name="ovule_position",
        ),
        migrations.RenameField(
            model_name="fruit", old_name="seed_color_form", new_name="seed_color_shape",
        ),
        migrations.RenameField(
            model_name="fruit", old_name="seed_num", new_name="seed_number",
        ),
    ]
