# Generated by Django 3.0.8 on 2022-01-14 15:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("dive_content", "0115_bulk_alter_fruit"),
    ]

    operations = [
        migrations.RemoveField(model_name="fruit", name="winging_feature",),
    ]
