# Generated by Django 3.0.8 on 2022-01-21 00:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("dive_content", "0117_bulk_rename_stemroot"),
    ]

    operations = [
        migrations.AddField(
            model_name="stemroot",
            name="creep_lay_shoots",
            field=models.BooleanField(
                blank=True,
                choices=[(None, "None"), (True, "Ja"), (False, "Nein")],
                null=True,
                verbose_name="Kriech- und Legetriebe",
            ),
        ),
        migrations.AddField(
            model_name="stemroot",
            name="runners",
            field=models.BooleanField(
                blank=True,
                choices=[(None, "None"), (True, "Ja"), (False, "Nein")],
                null=True,
                verbose_name="Ausläufer (oberirdisch)",
            ),
        ),
        migrations.AddField(
            model_name="stemroot",
            name="trunk_features",
            field=models.TextField(
                blank=True,
                help_text="Mit eigenständigem Satzbau ausformulieren.",
                max_length=200,
                verbose_name="Stammmerkmale",
            ),
        ),
    ]
