# Generated by Django 3.0.8 on 2022-01-18 21:10

from django.db import migrations


FORWARDS = {"": None, "bil": True, "kei": False}
REVERSE = {v: k for k, v in FORWARDS.items()}


def bulk_populate_stemroot_fields_forwards(apps, schema_editor):
    """
    Populate StemRoot model creep_lay_shoots fields with creep_lay_shoots_to_be_replaced
    values and runners fields with runners_to_be_replaced values.
    """
    StemRoot = apps.get_model("dive_content", "StemRoot")

    objects = list(StemRoot.objects.all())
    for obj in objects:
        obj.creep_lay_shoots = FORWARDS[obj.creep_lay_shoots_to_be_replaced]
        obj.runners = FORWARDS[obj.runners_to_be_replaced]
    StemRoot.objects.bulk_update(objects, ["creep_lay_shoots", "runners"])


def bulk_populate_stemroot_fields_reverse(apps, schema_editor):
    """
    Populate StemRoot model creep_lay_shoots_to_be_replaced fields with creep_lay_shoots
    values and runners_to_be_replaced fields runners values.
    """
    StemRoot = apps.get_model("dive_content", "StemRoot")

    objects = list(StemRoot.objects.all())
    for obj in objects:
        obj.creep_lay_shoots_to_be_replaced = REVERSE[obj.creep_lay_shoots]
        obj.runners_to_be_replaced = REVERSE[obj.runners]
    StemRoot.objects.bulk_update(
        objects, ["creep_lay_shoots_to_be_replaced", "runners_to_be_replaced"]
    )


class Migration(migrations.Migration):

    dependencies = [
        ("dive_content", "0119_bulk_alter_stemroot"),
    ]

    operations = [
        migrations.RunPython(
            bulk_populate_stemroot_fields_forwards,
            bulk_populate_stemroot_fields_reverse,
        ),
    ]
