# Generated by Django 3.0.8 on 2022-01-25 00:39

from django.db import migrations


def prune_leaf_basal_leaf_rosette(apps, schema_editor):
    Leaf = apps.get_model("dive_content", "Leaf")

    objects = list(Leaf.objects.exclude(basal_leaf_rosette=""))
    for obj in objects:
        obj.basal_leaf_rosette = ""
    Leaf.objects.bulk_update(objects, ["basal_leaf_rosette"])


def prune_leaf_simple_leaf_incision_depth(apps, schema_editor):
    Leaf = apps.get_model("dive_content", "Leaf")

    for obj in Leaf.objects.filter(simple_leaf_incision_depth__contains=["get"]):
        obj.simple_leaf_incision_depth.remove("get")
        obj.save()


class Migration(migrations.Migration):

    dependencies = [
        ("dive_content", "0122_bulk_rename_leaf"),
    ]

    operations = [
        migrations.RunPython(prune_leaf_basal_leaf_rosette, migrations.RunPython.noop),
        migrations.RunPython(
            prune_leaf_simple_leaf_incision_depth, migrations.RunPython.noop
        ),
    ]
