# Generated by Django 3.0.8 on 2022-01-27 10:38

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("dive_content", "0126_bulk_remove_leaf"),
    ]

    operations = [
        migrations.AddField(
            model_name="leaf",
            name="leaflet_number",
            field=models.CharField(
                blank=True, max_length=10, verbose_name="Anzahl (Blättchen)"
            ),
        ),
        migrations.AddField(
            model_name="leaf",
            name="leaflet_shape",
            field=django.contrib.postgres.fields.ArrayField(
                base_field=models.CharField(
                    choices=[
                        ("bin", "binsenartig"),
                        ("bor", "borstenförmig/borstlich"),
                        ("dre", "dreieckig"),
                        ("eif", "eiförmig"),
                        ("eil", "eilanzettlich"),
                        ("ell", "elliptisch"),
                        ("fad", "fadenförmig/fädlich"),
                        ("gei", "geigenförmig"),
                        ("her", "herzförmig"),
                        ("kei", "keilförmig"),
                        ("kre", "kreisrund"),
                        ("lae", "länglich"),
                        ("len", "lanzettlich"),
                        ("lin", "linealisch/lineal"),
                        ("nad", "nadelförmig"),
                        ("nie", "nierenförmig"),
                        ("pfe", "pfeilförmig"),
                        ("pfr", "pfriemlich"),
                        ("rau", "rautenförmig/rhombisch"),
                        ("roe", "röhrig"),
                        ("run", "rundlich"),
                        ("sil", "schildförmig"),
                        ("sup", "schuppenförmig"),
                        ("ser", "schwertförmig"),
                        ("spa", "spatelförmig/spatelig"),
                        ("spi", "spießförmig"),
                        ("ver", "verkehrteiförmig"),
                        ("vhe", "verkehrtherzförmig"),
                    ],
                    max_length=3,
                ),
                blank=True,
                default=list,
                size=2,
                verbose_name="Gestalt (Blättchen)",
            ),
        ),
        migrations.AddField(
            model_name="leaf",
            name="stipule",
            field=models.TextField(
                blank=True,
                help_text="Mit eigenständigem Satzbau ausformulieren.",
                max_length=200,
                verbose_name="Nebenblatt",
            ),
        ),
    ]
