# Generated by Django 3.0.8 on 2022-01-21 15:14

from django.db import migrations


def migrate_Photograph_to_MediaObject(apps, schema_editor):
    """
    Populate tree_node fields with systematics values.
    """
    Photograph = apps.get_model("photograph", "Photograph")
    MediaObject = apps.get_model("media_object", "MediaObject")

    # since there is no filterable backwards relation for `profile`
    for photo in Photograph.objects.all():
        # We can not access the profile relation in the migration for whatever
        # reason.
        # So just create MediaObjects from Photographs which are releated via a content_type
        if photo.object_id:
            _file = photo.img.file
            # get the original file name without path remnants
            _file.name = _file.name.split("/")[-1]
            audio_file = None
            if photo.audio:
                audio_file = photo.audio

            _dzi_file = None
            if photo.dzi_option:
                _dzi_file = photo.dzi_file

            MediaObject.objects.create(
                profile_position=photo.profile_position,
                media_format="image",
                file=_file,
                dzi_option=photo.dzi_option,
                dzi_file=_dzi_file,
                img_original_width=photo.img_original_width,
                img_original_height=photo.img_original_height,
                img_original_scale=photo.img_original_scale,
                img_alt=photo.img_alt,
                description=photo.description,
                audio=audio_file,
                date=photo.date,
                author=photo.author,
                license=photo.license,
                content_type=photo.content_type,
                object_id=photo.object_id,
            )


def migrate_MediaObject_to_Photograph(apps, schema_editor):

    Photograph = apps.get_model("photograph", "Photograph")
    MediaObject = apps.get_model("media_object", "MediaObject")

    # we need too loop over all MediaObjects which are images
    # since there is no filterable backwards relation for `profile`
    for media_obj in MediaObject.objects.filter(media_format="image"):
        if media_obj.object_id:
            _file = media_obj.file.file
            # get the original file name without path remnants
            _file.name = _file.name.split("/")[-1]
            audio_file = None
            if media_obj.audio:
                audio_file = media_obj.audio
                audio_file.name = audio_file.name.split("/")[-1]

            Photograph.objects.create(
                profile_position=media_obj.profile_position,
                img=_file,
                img_original_width=media_obj.img_original_width,
                img_original_height=media_obj.img_original_height,
                img_original_scale=media_obj.img_original_scale,
                img_alt=media_obj.img_alt,
                description=media_obj.description,
                audio=audio_file,
                date=media_obj.date,
                author=media_obj.author,
                license=media_obj.license,
                content_type=media_obj.content_type,
                object_id=media_obj.object_id,
            )


class Migration(migrations.Migration):

    dependencies = [
        ('dive_content', '0127_bulk_add_leaf'),
        ("photograph", "0006_add_profile_position_field"),
        ("media_object", "0002_audiovideomediaobject_imagemediaobject")
    ]

    operations = [
        migrations.RunPython(
            migrate_Photograph_to_MediaObject, migrate_MediaObject_to_Photograph
        ),
    ]
